################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/fntsrc/u8g_font_04b_03.c \
../Drivers/fntsrc/u8g_font_04b_03b.c \
../Drivers/fntsrc/u8g_font_04b_03bn.c \
../Drivers/fntsrc/u8g_font_04b_03br.c \
../Drivers/fntsrc/u8g_font_04b_03n.c \
../Drivers/fntsrc/u8g_font_04b_03r.c \
../Drivers/fntsrc/u8g_font_04b_24.c \
../Drivers/fntsrc/u8g_font_04b_24n.c \
../Drivers/fntsrc/u8g_font_04b_24r.c \
../Drivers/fntsrc/u8g_font_10x20.c \
../Drivers/fntsrc/u8g_font_10x20_67_75.c \
../Drivers/fntsrc/u8g_font_10x20_75r.c \
../Drivers/fntsrc/u8g_font_10x20_78_79.c \
../Drivers/fntsrc/u8g_font_10x20r.c \
../Drivers/fntsrc/u8g_font_4x6.c \
../Drivers/fntsrc/u8g_font_4x6r.c \
../Drivers/fntsrc/u8g_font_5x7.c \
../Drivers/fntsrc/u8g_font_5x7r.c \
../Drivers/fntsrc/u8g_font_5x8.c \
../Drivers/fntsrc/u8g_font_5x8r.c \
../Drivers/fntsrc/u8g_font_6x10.c \
../Drivers/fntsrc/u8g_font_6x10r.c \
../Drivers/fntsrc/u8g_font_6x12.c \
../Drivers/fntsrc/u8g_font_6x12_67_75.c \
../Drivers/fntsrc/u8g_font_6x12_75r.c \
../Drivers/fntsrc/u8g_font_6x12_78_79.c \
../Drivers/fntsrc/u8g_font_6x12r.c \
../Drivers/fntsrc/u8g_font_6x13.c \
../Drivers/fntsrc/u8g_font_6x13B.c \
../Drivers/fntsrc/u8g_font_6x13Br.c \
../Drivers/fntsrc/u8g_font_6x13O.c \
../Drivers/fntsrc/u8g_font_6x13Or.c \
../Drivers/fntsrc/u8g_font_6x13_67_75.c \
../Drivers/fntsrc/u8g_font_6x13_75r.c \
../Drivers/fntsrc/u8g_font_6x13_78_79.c \
../Drivers/fntsrc/u8g_font_6x13r.c \
../Drivers/fntsrc/u8g_font_7x13.c \
../Drivers/fntsrc/u8g_font_7x13B.c \
../Drivers/fntsrc/u8g_font_7x13Br.c \
../Drivers/fntsrc/u8g_font_7x13O.c \
../Drivers/fntsrc/u8g_font_7x13Or.c \
../Drivers/fntsrc/u8g_font_7x13_67_75.c \
../Drivers/fntsrc/u8g_font_7x13_75r.c \
../Drivers/fntsrc/u8g_font_7x13r.c \
../Drivers/fntsrc/u8g_font_7x14.c \
../Drivers/fntsrc/u8g_font_7x14B.c \
../Drivers/fntsrc/u8g_font_7x14Br.c \
../Drivers/fntsrc/u8g_font_7x14r.c \
../Drivers/fntsrc/u8g_font_8x13.c \
../Drivers/fntsrc/u8g_font_8x13B.c \
../Drivers/fntsrc/u8g_font_8x13Br.c \
../Drivers/fntsrc/u8g_font_8x13O.c \
../Drivers/fntsrc/u8g_font_8x13Or.c \
../Drivers/fntsrc/u8g_font_8x13_67_75.c \
../Drivers/fntsrc/u8g_font_8x13_75r.c \
../Drivers/fntsrc/u8g_font_8x13r.c \
../Drivers/fntsrc/u8g_font_9x15.c \
../Drivers/fntsrc/u8g_font_9x15B.c \
../Drivers/fntsrc/u8g_font_9x15Br.c \
../Drivers/fntsrc/u8g_font_9x15_67_75.c \
../Drivers/fntsrc/u8g_font_9x15_75r.c \
../Drivers/fntsrc/u8g_font_9x15_78_79.c \
../Drivers/fntsrc/u8g_font_9x15r.c \
../Drivers/fntsrc/u8g_font_9x18.c \
../Drivers/fntsrc/u8g_font_9x18B.c \
../Drivers/fntsrc/u8g_font_9x18Br.c \
../Drivers/fntsrc/u8g_font_9x18_67_75.c \
../Drivers/fntsrc/u8g_font_9x18_75r.c \
../Drivers/fntsrc/u8g_font_9x18_78_79.c \
../Drivers/fntsrc/u8g_font_9x18r.c \
../Drivers/fntsrc/u8g_font_baby.c \
../Drivers/fntsrc/u8g_font_babyn.c \
../Drivers/fntsrc/u8g_font_babyr.c \
../Drivers/fntsrc/u8g_font_blipfest_07.c \
../Drivers/fntsrc/u8g_font_blipfest_07n.c \
../Drivers/fntsrc/u8g_font_blipfest_07r.c \
../Drivers/fntsrc/u8g_font_chikita.c \
../Drivers/fntsrc/u8g_font_chikitan.c \
../Drivers/fntsrc/u8g_font_chikitar.c \
../Drivers/fntsrc/u8g_font_courb08.c \
../Drivers/fntsrc/u8g_font_courb08r.c \
../Drivers/fntsrc/u8g_font_courb10.c \
../Drivers/fntsrc/u8g_font_courb10r.c \
../Drivers/fntsrc/u8g_font_courb12.c \
../Drivers/fntsrc/u8g_font_courb12r.c \
../Drivers/fntsrc/u8g_font_courb14.c \
../Drivers/fntsrc/u8g_font_courb14r.c \
../Drivers/fntsrc/u8g_font_courb18.c \
../Drivers/fntsrc/u8g_font_courb18r.c \
../Drivers/fntsrc/u8g_font_courb24.c \
../Drivers/fntsrc/u8g_font_courb24r.c \
../Drivers/fntsrc/u8g_font_courb4n.c \
../Drivers/fntsrc/u8g_font_courr08.c \
../Drivers/fntsrc/u8g_font_courr08r.c \
../Drivers/fntsrc/u8g_font_courr10.c \
../Drivers/fntsrc/u8g_font_courr10r.c \
../Drivers/fntsrc/u8g_font_courr12.c \
../Drivers/fntsrc/u8g_font_courr12r.c \
../Drivers/fntsrc/u8g_font_courr14.c \
../Drivers/fntsrc/u8g_font_courr14r.c \
../Drivers/fntsrc/u8g_font_courr18.c \
../Drivers/fntsrc/u8g_font_courr18r.c \
../Drivers/fntsrc/u8g_font_courr24.c \
../Drivers/fntsrc/u8g_font_courr24n.c \
../Drivers/fntsrc/u8g_font_courr24r.c \
../Drivers/fntsrc/u8g_font_cu12.c \
../Drivers/fntsrc/u8g_font_cu12_67_75.c \
../Drivers/fntsrc/u8g_font_cu12_75r.c \
../Drivers/fntsrc/u8g_font_cursor.c \
../Drivers/fntsrc/u8g_font_cursorr.c \
../Drivers/fntsrc/u8g_font_fixed_v0.c \
../Drivers/fntsrc/u8g_font_fixed_v0n.c \
../Drivers/fntsrc/u8g_font_fixed_v0r.c \
../Drivers/fntsrc/u8g_font_freedoomr10r.c \
../Drivers/fntsrc/u8g_font_freedoomr25n.c \
../Drivers/fntsrc/u8g_font_fub11.c \
../Drivers/fntsrc/u8g_font_fub11n.c \
../Drivers/fntsrc/u8g_font_fub11r.c \
../Drivers/fntsrc/u8g_font_fub14.c \
../Drivers/fntsrc/u8g_font_fub14n.c \
../Drivers/fntsrc/u8g_font_fub14r.c \
../Drivers/fntsrc/u8g_font_fub17.c \
../Drivers/fntsrc/u8g_font_fub17n.c \
../Drivers/fntsrc/u8g_font_fub17r.c \
../Drivers/fntsrc/u8g_font_fub20.c \
../Drivers/fntsrc/u8g_font_fub20n.c \
../Drivers/fntsrc/u8g_font_fub20r.c \
../Drivers/fntsrc/u8g_font_fub25.c \
../Drivers/fntsrc/u8g_font_fub25n.c \
../Drivers/fntsrc/u8g_font_fub25r.c \
../Drivers/fntsrc/u8g_font_fub30.c \
../Drivers/fntsrc/u8g_font_fub30n.c \
../Drivers/fntsrc/u8g_font_fub30r.c \
../Drivers/fntsrc/u8g_font_fub35n.c \
../Drivers/fntsrc/u8g_font_fub42n.c \
../Drivers/fntsrc/u8g_font_fub49n.c \
../Drivers/fntsrc/u8g_font_fur11.c \
../Drivers/fntsrc/u8g_font_fur11n.c \
../Drivers/fntsrc/u8g_font_fur11r.c \
../Drivers/fntsrc/u8g_font_fur14.c \
../Drivers/fntsrc/u8g_font_fur14n.c \
../Drivers/fntsrc/u8g_font_fur14r.c \
../Drivers/fntsrc/u8g_font_fur17.c \
../Drivers/fntsrc/u8g_font_fur17n.c \
../Drivers/fntsrc/u8g_font_fur17r.c \
../Drivers/fntsrc/u8g_font_fur20.c \
../Drivers/fntsrc/u8g_font_fur20n.c \
../Drivers/fntsrc/u8g_font_fur20r.c \
../Drivers/fntsrc/u8g_font_fur25.c \
../Drivers/fntsrc/u8g_font_fur25n.c \
../Drivers/fntsrc/u8g_font_fur25r.c \
../Drivers/fntsrc/u8g_font_fur30.c \
../Drivers/fntsrc/u8g_font_fur30n.c \
../Drivers/fntsrc/u8g_font_fur30r.c \
../Drivers/fntsrc/u8g_font_fur35n.c \
../Drivers/fntsrc/u8g_font_fur42n.c \
../Drivers/fntsrc/u8g_font_fur49n.c \
../Drivers/fntsrc/u8g_font_gdb11.c \
../Drivers/fntsrc/u8g_font_gdb11n.c \
../Drivers/fntsrc/u8g_font_gdb11r.c \
../Drivers/fntsrc/u8g_font_gdb12.c \
../Drivers/fntsrc/u8g_font_gdb12n.c \
../Drivers/fntsrc/u8g_font_gdb12r.c \
../Drivers/fntsrc/u8g_font_gdb14.c \
../Drivers/fntsrc/u8g_font_gdb14n.c \
../Drivers/fntsrc/u8g_font_gdb14r.c \
../Drivers/fntsrc/u8g_font_gdb17.c \
../Drivers/fntsrc/u8g_font_gdb17n.c \
../Drivers/fntsrc/u8g_font_gdb17r.c \
../Drivers/fntsrc/u8g_font_gdb20.c \
../Drivers/fntsrc/u8g_font_gdb20n.c \
../Drivers/fntsrc/u8g_font_gdb20r.c \
../Drivers/fntsrc/u8g_font_gdb25.c \
../Drivers/fntsrc/u8g_font_gdb25n.c \
../Drivers/fntsrc/u8g_font_gdb25r.c \
../Drivers/fntsrc/u8g_font_gdb30.c \
../Drivers/fntsrc/u8g_font_gdb30n.c \
../Drivers/fntsrc/u8g_font_gdb30r.c \
../Drivers/fntsrc/u8g_font_gdr10.c \
../Drivers/fntsrc/u8g_font_gdr10n.c \
../Drivers/fntsrc/u8g_font_gdr10r.c \
../Drivers/fntsrc/u8g_font_gdr11.c \
../Drivers/fntsrc/u8g_font_gdr11n.c \
../Drivers/fntsrc/u8g_font_gdr11r.c \
../Drivers/fntsrc/u8g_font_gdr12.c \
../Drivers/fntsrc/u8g_font_gdr12n.c \
../Drivers/fntsrc/u8g_font_gdr12r.c \
../Drivers/fntsrc/u8g_font_gdr14.c \
../Drivers/fntsrc/u8g_font_gdr14n.c \
../Drivers/fntsrc/u8g_font_gdr14r.c \
../Drivers/fntsrc/u8g_font_gdr17.c \
../Drivers/fntsrc/u8g_font_gdr17n.c \
../Drivers/fntsrc/u8g_font_gdr17r.c \
../Drivers/fntsrc/u8g_font_gdr20.c \
../Drivers/fntsrc/u8g_font_gdr20n.c \
../Drivers/fntsrc/u8g_font_gdr20r.c \
../Drivers/fntsrc/u8g_font_gdr25.c \
../Drivers/fntsrc/u8g_font_gdr25n.c \
../Drivers/fntsrc/u8g_font_gdr25r.c \
../Drivers/fntsrc/u8g_font_gdr30.c \
../Drivers/fntsrc/u8g_font_gdr30n.c \
../Drivers/fntsrc/u8g_font_gdr30r.c \
../Drivers/fntsrc/u8g_font_gdr9.c \
../Drivers/fntsrc/u8g_font_gdr9n.c \
../Drivers/fntsrc/u8g_font_gdr9r.c \
../Drivers/fntsrc/u8g_font_helvb08.c \
../Drivers/fntsrc/u8g_font_helvb08n.c \
../Drivers/fntsrc/u8g_font_helvb08r.c \
../Drivers/fntsrc/u8g_font_helvb10.c \
../Drivers/fntsrc/u8g_font_helvb10n.c \
../Drivers/fntsrc/u8g_font_helvb10r.c \
../Drivers/fntsrc/u8g_font_helvb12.c \
../Drivers/fntsrc/u8g_font_helvb12n.c \
../Drivers/fntsrc/u8g_font_helvb12r.c \
../Drivers/fntsrc/u8g_font_helvb14.c \
../Drivers/fntsrc/u8g_font_helvb14n.c \
../Drivers/fntsrc/u8g_font_helvb14r.c \
../Drivers/fntsrc/u8g_font_helvb18.c \
../Drivers/fntsrc/u8g_font_helvb18n.c \
../Drivers/fntsrc/u8g_font_helvb18r.c \
../Drivers/fntsrc/u8g_font_helvb24.c \
../Drivers/fntsrc/u8g_font_helvb24n.c \
../Drivers/fntsrc/u8g_font_helvb24r.c \
../Drivers/fntsrc/u8g_font_helvr08.c \
../Drivers/fntsrc/u8g_font_helvr08r.c \
../Drivers/fntsrc/u8g_font_helvr10.c \
../Drivers/fntsrc/u8g_font_helvr10r.c \
../Drivers/fntsrc/u8g_font_helvr12.c \
../Drivers/fntsrc/u8g_font_helvr12r.c \
../Drivers/fntsrc/u8g_font_helvr14.c \
../Drivers/fntsrc/u8g_font_helvr14r.c \
../Drivers/fntsrc/u8g_font_helvr18.c \
../Drivers/fntsrc/u8g_font_helvr18r.c \
../Drivers/fntsrc/u8g_font_helvr24.c \
../Drivers/fntsrc/u8g_font_helvr24n.c \
../Drivers/fntsrc/u8g_font_helvr24r.c \
../Drivers/fntsrc/u8g_font_lucasfont_alternate.c \
../Drivers/fntsrc/u8g_font_lucasfont_alternaten.c \
../Drivers/fntsrc/u8g_font_lucasfont_alternater.c \
../Drivers/fntsrc/u8g_font_m2icon_5.c \
../Drivers/fntsrc/u8g_font_m2icon_7.c \
../Drivers/fntsrc/u8g_font_m2icon_9.c \
../Drivers/fntsrc/u8g_font_micro.c \
../Drivers/fntsrc/u8g_font_ncenb08.c \
../Drivers/fntsrc/u8g_font_ncenb08r.c \
../Drivers/fntsrc/u8g_font_ncenb10.c \
../Drivers/fntsrc/u8g_font_ncenb10r.c \
../Drivers/fntsrc/u8g_font_ncenb12.c \
../Drivers/fntsrc/u8g_font_ncenb12r.c \
../Drivers/fntsrc/u8g_font_ncenb14.c \
../Drivers/fntsrc/u8g_font_ncenb14r.c \
../Drivers/fntsrc/u8g_font_ncenb18.c \
../Drivers/fntsrc/u8g_font_ncenb18r.c \
../Drivers/fntsrc/u8g_font_ncenb24.c \
../Drivers/fntsrc/u8g_font_ncenb24n.c \
../Drivers/fntsrc/u8g_font_ncenb24r.c \
../Drivers/fntsrc/u8g_font_ncenr08.c \
../Drivers/fntsrc/u8g_font_ncenr08r.c \
../Drivers/fntsrc/u8g_font_ncenr10.c \
../Drivers/fntsrc/u8g_font_ncenr10r.c \
../Drivers/fntsrc/u8g_font_ncenr12.c \
../Drivers/fntsrc/u8g_font_ncenr12r.c \
../Drivers/fntsrc/u8g_font_ncenr14.c \
../Drivers/fntsrc/u8g_font_ncenr14r.c \
../Drivers/fntsrc/u8g_font_ncenr18.c \
../Drivers/fntsrc/u8g_font_ncenr18r.c \
../Drivers/fntsrc/u8g_font_ncenr24.c \
../Drivers/fntsrc/u8g_font_ncenr24n.c \
../Drivers/fntsrc/u8g_font_ncenr24r.c \
../Drivers/fntsrc/u8g_font_orgv01.c \
../Drivers/fntsrc/u8g_font_orgv01n.c \
../Drivers/fntsrc/u8g_font_orgv01r.c \
../Drivers/fntsrc/u8g_font_osb18.c \
../Drivers/fntsrc/u8g_font_osb18n.c \
../Drivers/fntsrc/u8g_font_osb18r.c \
../Drivers/fntsrc/u8g_font_osb21.c \
../Drivers/fntsrc/u8g_font_osb21n.c \
../Drivers/fntsrc/u8g_font_osb21r.c \
../Drivers/fntsrc/u8g_font_osb26.c \
../Drivers/fntsrc/u8g_font_osb26n.c \
../Drivers/fntsrc/u8g_font_osb26r.c \
../Drivers/fntsrc/u8g_font_osb29.c \
../Drivers/fntsrc/u8g_font_osb29n.c \
../Drivers/fntsrc/u8g_font_osb29r.c \
../Drivers/fntsrc/u8g_font_osb35.c \
../Drivers/fntsrc/u8g_font_osb35n.c \
../Drivers/fntsrc/u8g_font_osb35r.c \
../Drivers/fntsrc/u8g_font_osr18.c \
../Drivers/fntsrc/u8g_font_osr18n.c \
../Drivers/fntsrc/u8g_font_osr18r.c \
../Drivers/fntsrc/u8g_font_osr21.c \
../Drivers/fntsrc/u8g_font_osr21n.c \
../Drivers/fntsrc/u8g_font_osr21r.c \
../Drivers/fntsrc/u8g_font_osr26.c \
../Drivers/fntsrc/u8g_font_osr26n.c \
../Drivers/fntsrc/u8g_font_osr26r.c \
../Drivers/fntsrc/u8g_font_osr29.c \
../Drivers/fntsrc/u8g_font_osr29n.c \
../Drivers/fntsrc/u8g_font_osr29r.c \
../Drivers/fntsrc/u8g_font_osr35.c \
../Drivers/fntsrc/u8g_font_osr35n.c \
../Drivers/fntsrc/u8g_font_osr35r.c \
../Drivers/fntsrc/u8g_font_p01type.c \
../Drivers/fntsrc/u8g_font_p01typen.c \
../Drivers/fntsrc/u8g_font_p01typer.c \
../Drivers/fntsrc/u8g_font_pixelle_micro.c \
../Drivers/fntsrc/u8g_font_pixelle_micron.c \
../Drivers/fntsrc/u8g_font_pixelle_micror.c \
../Drivers/fntsrc/u8g_font_profont10.c \
../Drivers/fntsrc/u8g_font_profont10r.c \
../Drivers/fntsrc/u8g_font_profont11.c \
../Drivers/fntsrc/u8g_font_profont11r.c \
../Drivers/fntsrc/u8g_font_profont12.c \
../Drivers/fntsrc/u8g_font_profont12r.c \
../Drivers/fntsrc/u8g_font_profont15.c \
../Drivers/fntsrc/u8g_font_profont15r.c \
../Drivers/fntsrc/u8g_font_profont17.c \
../Drivers/fntsrc/u8g_font_profont17r.c \
../Drivers/fntsrc/u8g_font_profont22.c \
../Drivers/fntsrc/u8g_font_profont22r.c \
../Drivers/fntsrc/u8g_font_profont29.c \
../Drivers/fntsrc/u8g_font_profont29r.c \
../Drivers/fntsrc/u8g_font_robot_de_niro.c \
../Drivers/fntsrc/u8g_font_robot_de_niron.c \
../Drivers/fntsrc/u8g_font_robot_de_niror.c \
../Drivers/fntsrc/u8g_font_symb08.c \
../Drivers/fntsrc/u8g_font_symb08r.c \
../Drivers/fntsrc/u8g_font_symb10.c \
../Drivers/fntsrc/u8g_font_symb10r.c \
../Drivers/fntsrc/u8g_font_symb12.c \
../Drivers/fntsrc/u8g_font_symb12r.c \
../Drivers/fntsrc/u8g_font_symb14.c \
../Drivers/fntsrc/u8g_font_symb14r.c \
../Drivers/fntsrc/u8g_font_symb18.c \
../Drivers/fntsrc/u8g_font_symb18r.c \
../Drivers/fntsrc/u8g_font_symb24.c \
../Drivers/fntsrc/u8g_font_symb24r.c \
../Drivers/fntsrc/u8g_font_timb08.c \
../Drivers/fntsrc/u8g_font_timb08r.c \
../Drivers/fntsrc/u8g_font_timb10.c \
../Drivers/fntsrc/u8g_font_timb10r.c \
../Drivers/fntsrc/u8g_font_timb12.c \
../Drivers/fntsrc/u8g_font_timb12r.c \
../Drivers/fntsrc/u8g_font_timb14.c \
../Drivers/fntsrc/u8g_font_timb14r.c \
../Drivers/fntsrc/u8g_font_timb18.c \
../Drivers/fntsrc/u8g_font_timb18r.c \
../Drivers/fntsrc/u8g_font_timb24.c \
../Drivers/fntsrc/u8g_font_timb24n.c \
../Drivers/fntsrc/u8g_font_timb24r.c \
../Drivers/fntsrc/u8g_font_timr08.c \
../Drivers/fntsrc/u8g_font_timr08r.c \
../Drivers/fntsrc/u8g_font_timr10.c \
../Drivers/fntsrc/u8g_font_timr10r.c \
../Drivers/fntsrc/u8g_font_timr12.c \
../Drivers/fntsrc/u8g_font_timr12r.c \
../Drivers/fntsrc/u8g_font_timr14.c \
../Drivers/fntsrc/u8g_font_timr14r.c \
../Drivers/fntsrc/u8g_font_timr18.c \
../Drivers/fntsrc/u8g_font_timr18r.c \
../Drivers/fntsrc/u8g_font_timr24.c \
../Drivers/fntsrc/u8g_font_timr24n.c \
../Drivers/fntsrc/u8g_font_timr24r.c \
../Drivers/fntsrc/u8g_font_tpss.c \
../Drivers/fntsrc/u8g_font_tpssb.c \
../Drivers/fntsrc/u8g_font_tpssbn.c \
../Drivers/fntsrc/u8g_font_tpssbr.c \
../Drivers/fntsrc/u8g_font_tpssn.c \
../Drivers/fntsrc/u8g_font_tpssr.c \
../Drivers/fntsrc/u8g_font_trixel_square.c \
../Drivers/fntsrc/u8g_font_trixel_squaren.c \
../Drivers/fntsrc/u8g_font_trixel_squarer.c \
../Drivers/fntsrc/u8g_font_u8glib_4.c \
../Drivers/fntsrc/u8g_font_u8glib_4r.c \
../Drivers/fntsrc/u8g_font_unifont.c \
../Drivers/fntsrc/u8g_font_unifont_0_8.c \
../Drivers/fntsrc/u8g_font_unifont_12_13.c \
../Drivers/fntsrc/u8g_font_unifont_18_19.c \
../Drivers/fntsrc/u8g_font_unifont_2_3.c \
../Drivers/fntsrc/u8g_font_unifont_4_5.c \
../Drivers/fntsrc/u8g_font_unifont_67_75.c \
../Drivers/fntsrc/u8g_font_unifont_72_73.c \
../Drivers/fntsrc/u8g_font_unifont_75r.c \
../Drivers/fntsrc/u8g_font_unifont_76.c \
../Drivers/fntsrc/u8g_font_unifont_77.c \
../Drivers/fntsrc/u8g_font_unifont_78_79.c \
../Drivers/fntsrc/u8g_font_unifont_86.c \
../Drivers/fntsrc/u8g_font_unifont_8_9.c \
../Drivers/fntsrc/u8g_font_unifontr.c 

OBJS += \
./Drivers/fntsrc/u8g_font_04b_03.o \
./Drivers/fntsrc/u8g_font_04b_03b.o \
./Drivers/fntsrc/u8g_font_04b_03bn.o \
./Drivers/fntsrc/u8g_font_04b_03br.o \
./Drivers/fntsrc/u8g_font_04b_03n.o \
./Drivers/fntsrc/u8g_font_04b_03r.o \
./Drivers/fntsrc/u8g_font_04b_24.o \
./Drivers/fntsrc/u8g_font_04b_24n.o \
./Drivers/fntsrc/u8g_font_04b_24r.o \
./Drivers/fntsrc/u8g_font_10x20.o \
./Drivers/fntsrc/u8g_font_10x20_67_75.o \
./Drivers/fntsrc/u8g_font_10x20_75r.o \
./Drivers/fntsrc/u8g_font_10x20_78_79.o \
./Drivers/fntsrc/u8g_font_10x20r.o \
./Drivers/fntsrc/u8g_font_4x6.o \
./Drivers/fntsrc/u8g_font_4x6r.o \
./Drivers/fntsrc/u8g_font_5x7.o \
./Drivers/fntsrc/u8g_font_5x7r.o \
./Drivers/fntsrc/u8g_font_5x8.o \
./Drivers/fntsrc/u8g_font_5x8r.o \
./Drivers/fntsrc/u8g_font_6x10.o \
./Drivers/fntsrc/u8g_font_6x10r.o \
./Drivers/fntsrc/u8g_font_6x12.o \
./Drivers/fntsrc/u8g_font_6x12_67_75.o \
./Drivers/fntsrc/u8g_font_6x12_75r.o \
./Drivers/fntsrc/u8g_font_6x12_78_79.o \
./Drivers/fntsrc/u8g_font_6x12r.o \
./Drivers/fntsrc/u8g_font_6x13.o \
./Drivers/fntsrc/u8g_font_6x13B.o \
./Drivers/fntsrc/u8g_font_6x13Br.o \
./Drivers/fntsrc/u8g_font_6x13O.o \
./Drivers/fntsrc/u8g_font_6x13Or.o \
./Drivers/fntsrc/u8g_font_6x13_67_75.o \
./Drivers/fntsrc/u8g_font_6x13_75r.o \
./Drivers/fntsrc/u8g_font_6x13_78_79.o \
./Drivers/fntsrc/u8g_font_6x13r.o \
./Drivers/fntsrc/u8g_font_7x13.o \
./Drivers/fntsrc/u8g_font_7x13B.o \
./Drivers/fntsrc/u8g_font_7x13Br.o \
./Drivers/fntsrc/u8g_font_7x13O.o \
./Drivers/fntsrc/u8g_font_7x13Or.o \
./Drivers/fntsrc/u8g_font_7x13_67_75.o \
./Drivers/fntsrc/u8g_font_7x13_75r.o \
./Drivers/fntsrc/u8g_font_7x13r.o \
./Drivers/fntsrc/u8g_font_7x14.o \
./Drivers/fntsrc/u8g_font_7x14B.o \
./Drivers/fntsrc/u8g_font_7x14Br.o \
./Drivers/fntsrc/u8g_font_7x14r.o \
./Drivers/fntsrc/u8g_font_8x13.o \
./Drivers/fntsrc/u8g_font_8x13B.o \
./Drivers/fntsrc/u8g_font_8x13Br.o \
./Drivers/fntsrc/u8g_font_8x13O.o \
./Drivers/fntsrc/u8g_font_8x13Or.o \
./Drivers/fntsrc/u8g_font_8x13_67_75.o \
./Drivers/fntsrc/u8g_font_8x13_75r.o \
./Drivers/fntsrc/u8g_font_8x13r.o \
./Drivers/fntsrc/u8g_font_9x15.o \
./Drivers/fntsrc/u8g_font_9x15B.o \
./Drivers/fntsrc/u8g_font_9x15Br.o \
./Drivers/fntsrc/u8g_font_9x15_67_75.o \
./Drivers/fntsrc/u8g_font_9x15_75r.o \
./Drivers/fntsrc/u8g_font_9x15_78_79.o \
./Drivers/fntsrc/u8g_font_9x15r.o \
./Drivers/fntsrc/u8g_font_9x18.o \
./Drivers/fntsrc/u8g_font_9x18B.o \
./Drivers/fntsrc/u8g_font_9x18Br.o \
./Drivers/fntsrc/u8g_font_9x18_67_75.o \
./Drivers/fntsrc/u8g_font_9x18_75r.o \
./Drivers/fntsrc/u8g_font_9x18_78_79.o \
./Drivers/fntsrc/u8g_font_9x18r.o \
./Drivers/fntsrc/u8g_font_baby.o \
./Drivers/fntsrc/u8g_font_babyn.o \
./Drivers/fntsrc/u8g_font_babyr.o \
./Drivers/fntsrc/u8g_font_blipfest_07.o \
./Drivers/fntsrc/u8g_font_blipfest_07n.o \
./Drivers/fntsrc/u8g_font_blipfest_07r.o \
./Drivers/fntsrc/u8g_font_chikita.o \
./Drivers/fntsrc/u8g_font_chikitan.o \
./Drivers/fntsrc/u8g_font_chikitar.o \
./Drivers/fntsrc/u8g_font_courb08.o \
./Drivers/fntsrc/u8g_font_courb08r.o \
./Drivers/fntsrc/u8g_font_courb10.o \
./Drivers/fntsrc/u8g_font_courb10r.o \
./Drivers/fntsrc/u8g_font_courb12.o \
./Drivers/fntsrc/u8g_font_courb12r.o \
./Drivers/fntsrc/u8g_font_courb14.o \
./Drivers/fntsrc/u8g_font_courb14r.o \
./Drivers/fntsrc/u8g_font_courb18.o \
./Drivers/fntsrc/u8g_font_courb18r.o \
./Drivers/fntsrc/u8g_font_courb24.o \
./Drivers/fntsrc/u8g_font_courb24r.o \
./Drivers/fntsrc/u8g_font_courb4n.o \
./Drivers/fntsrc/u8g_font_courr08.o \
./Drivers/fntsrc/u8g_font_courr08r.o \
./Drivers/fntsrc/u8g_font_courr10.o \
./Drivers/fntsrc/u8g_font_courr10r.o \
./Drivers/fntsrc/u8g_font_courr12.o \
./Drivers/fntsrc/u8g_font_courr12r.o \
./Drivers/fntsrc/u8g_font_courr14.o \
./Drivers/fntsrc/u8g_font_courr14r.o \
./Drivers/fntsrc/u8g_font_courr18.o \
./Drivers/fntsrc/u8g_font_courr18r.o \
./Drivers/fntsrc/u8g_font_courr24.o \
./Drivers/fntsrc/u8g_font_courr24n.o \
./Drivers/fntsrc/u8g_font_courr24r.o \
./Drivers/fntsrc/u8g_font_cu12.o \
./Drivers/fntsrc/u8g_font_cu12_67_75.o \
./Drivers/fntsrc/u8g_font_cu12_75r.o \
./Drivers/fntsrc/u8g_font_cursor.o \
./Drivers/fntsrc/u8g_font_cursorr.o \
./Drivers/fntsrc/u8g_font_fixed_v0.o \
./Drivers/fntsrc/u8g_font_fixed_v0n.o \
./Drivers/fntsrc/u8g_font_fixed_v0r.o \
./Drivers/fntsrc/u8g_font_freedoomr10r.o \
./Drivers/fntsrc/u8g_font_freedoomr25n.o \
./Drivers/fntsrc/u8g_font_fub11.o \
./Drivers/fntsrc/u8g_font_fub11n.o \
./Drivers/fntsrc/u8g_font_fub11r.o \
./Drivers/fntsrc/u8g_font_fub14.o \
./Drivers/fntsrc/u8g_font_fub14n.o \
./Drivers/fntsrc/u8g_font_fub14r.o \
./Drivers/fntsrc/u8g_font_fub17.o \
./Drivers/fntsrc/u8g_font_fub17n.o \
./Drivers/fntsrc/u8g_font_fub17r.o \
./Drivers/fntsrc/u8g_font_fub20.o \
./Drivers/fntsrc/u8g_font_fub20n.o \
./Drivers/fntsrc/u8g_font_fub20r.o \
./Drivers/fntsrc/u8g_font_fub25.o \
./Drivers/fntsrc/u8g_font_fub25n.o \
./Drivers/fntsrc/u8g_font_fub25r.o \
./Drivers/fntsrc/u8g_font_fub30.o \
./Drivers/fntsrc/u8g_font_fub30n.o \
./Drivers/fntsrc/u8g_font_fub30r.o \
./Drivers/fntsrc/u8g_font_fub35n.o \
./Drivers/fntsrc/u8g_font_fub42n.o \
./Drivers/fntsrc/u8g_font_fub49n.o \
./Drivers/fntsrc/u8g_font_fur11.o \
./Drivers/fntsrc/u8g_font_fur11n.o \
./Drivers/fntsrc/u8g_font_fur11r.o \
./Drivers/fntsrc/u8g_font_fur14.o \
./Drivers/fntsrc/u8g_font_fur14n.o \
./Drivers/fntsrc/u8g_font_fur14r.o \
./Drivers/fntsrc/u8g_font_fur17.o \
./Drivers/fntsrc/u8g_font_fur17n.o \
./Drivers/fntsrc/u8g_font_fur17r.o \
./Drivers/fntsrc/u8g_font_fur20.o \
./Drivers/fntsrc/u8g_font_fur20n.o \
./Drivers/fntsrc/u8g_font_fur20r.o \
./Drivers/fntsrc/u8g_font_fur25.o \
./Drivers/fntsrc/u8g_font_fur25n.o \
./Drivers/fntsrc/u8g_font_fur25r.o \
./Drivers/fntsrc/u8g_font_fur30.o \
./Drivers/fntsrc/u8g_font_fur30n.o \
./Drivers/fntsrc/u8g_font_fur30r.o \
./Drivers/fntsrc/u8g_font_fur35n.o \
./Drivers/fntsrc/u8g_font_fur42n.o \
./Drivers/fntsrc/u8g_font_fur49n.o \
./Drivers/fntsrc/u8g_font_gdb11.o \
./Drivers/fntsrc/u8g_font_gdb11n.o \
./Drivers/fntsrc/u8g_font_gdb11r.o \
./Drivers/fntsrc/u8g_font_gdb12.o \
./Drivers/fntsrc/u8g_font_gdb12n.o \
./Drivers/fntsrc/u8g_font_gdb12r.o \
./Drivers/fntsrc/u8g_font_gdb14.o \
./Drivers/fntsrc/u8g_font_gdb14n.o \
./Drivers/fntsrc/u8g_font_gdb14r.o \
./Drivers/fntsrc/u8g_font_gdb17.o \
./Drivers/fntsrc/u8g_font_gdb17n.o \
./Drivers/fntsrc/u8g_font_gdb17r.o \
./Drivers/fntsrc/u8g_font_gdb20.o \
./Drivers/fntsrc/u8g_font_gdb20n.o \
./Drivers/fntsrc/u8g_font_gdb20r.o \
./Drivers/fntsrc/u8g_font_gdb25.o \
./Drivers/fntsrc/u8g_font_gdb25n.o \
./Drivers/fntsrc/u8g_font_gdb25r.o \
./Drivers/fntsrc/u8g_font_gdb30.o \
./Drivers/fntsrc/u8g_font_gdb30n.o \
./Drivers/fntsrc/u8g_font_gdb30r.o \
./Drivers/fntsrc/u8g_font_gdr10.o \
./Drivers/fntsrc/u8g_font_gdr10n.o \
./Drivers/fntsrc/u8g_font_gdr10r.o \
./Drivers/fntsrc/u8g_font_gdr11.o \
./Drivers/fntsrc/u8g_font_gdr11n.o \
./Drivers/fntsrc/u8g_font_gdr11r.o \
./Drivers/fntsrc/u8g_font_gdr12.o \
./Drivers/fntsrc/u8g_font_gdr12n.o \
./Drivers/fntsrc/u8g_font_gdr12r.o \
./Drivers/fntsrc/u8g_font_gdr14.o \
./Drivers/fntsrc/u8g_font_gdr14n.o \
./Drivers/fntsrc/u8g_font_gdr14r.o \
./Drivers/fntsrc/u8g_font_gdr17.o \
./Drivers/fntsrc/u8g_font_gdr17n.o \
./Drivers/fntsrc/u8g_font_gdr17r.o \
./Drivers/fntsrc/u8g_font_gdr20.o \
./Drivers/fntsrc/u8g_font_gdr20n.o \
./Drivers/fntsrc/u8g_font_gdr20r.o \
./Drivers/fntsrc/u8g_font_gdr25.o \
./Drivers/fntsrc/u8g_font_gdr25n.o \
./Drivers/fntsrc/u8g_font_gdr25r.o \
./Drivers/fntsrc/u8g_font_gdr30.o \
./Drivers/fntsrc/u8g_font_gdr30n.o \
./Drivers/fntsrc/u8g_font_gdr30r.o \
./Drivers/fntsrc/u8g_font_gdr9.o \
./Drivers/fntsrc/u8g_font_gdr9n.o \
./Drivers/fntsrc/u8g_font_gdr9r.o \
./Drivers/fntsrc/u8g_font_helvb08.o \
./Drivers/fntsrc/u8g_font_helvb08n.o \
./Drivers/fntsrc/u8g_font_helvb08r.o \
./Drivers/fntsrc/u8g_font_helvb10.o \
./Drivers/fntsrc/u8g_font_helvb10n.o \
./Drivers/fntsrc/u8g_font_helvb10r.o \
./Drivers/fntsrc/u8g_font_helvb12.o \
./Drivers/fntsrc/u8g_font_helvb12n.o \
./Drivers/fntsrc/u8g_font_helvb12r.o \
./Drivers/fntsrc/u8g_font_helvb14.o \
./Drivers/fntsrc/u8g_font_helvb14n.o \
./Drivers/fntsrc/u8g_font_helvb14r.o \
./Drivers/fntsrc/u8g_font_helvb18.o \
./Drivers/fntsrc/u8g_font_helvb18n.o \
./Drivers/fntsrc/u8g_font_helvb18r.o \
./Drivers/fntsrc/u8g_font_helvb24.o \
./Drivers/fntsrc/u8g_font_helvb24n.o \
./Drivers/fntsrc/u8g_font_helvb24r.o \
./Drivers/fntsrc/u8g_font_helvr08.o \
./Drivers/fntsrc/u8g_font_helvr08r.o \
./Drivers/fntsrc/u8g_font_helvr10.o \
./Drivers/fntsrc/u8g_font_helvr10r.o \
./Drivers/fntsrc/u8g_font_helvr12.o \
./Drivers/fntsrc/u8g_font_helvr12r.o \
./Drivers/fntsrc/u8g_font_helvr14.o \
./Drivers/fntsrc/u8g_font_helvr14r.o \
./Drivers/fntsrc/u8g_font_helvr18.o \
./Drivers/fntsrc/u8g_font_helvr18r.o \
./Drivers/fntsrc/u8g_font_helvr24.o \
./Drivers/fntsrc/u8g_font_helvr24n.o \
./Drivers/fntsrc/u8g_font_helvr24r.o \
./Drivers/fntsrc/u8g_font_lucasfont_alternate.o \
./Drivers/fntsrc/u8g_font_lucasfont_alternaten.o \
./Drivers/fntsrc/u8g_font_lucasfont_alternater.o \
./Drivers/fntsrc/u8g_font_m2icon_5.o \
./Drivers/fntsrc/u8g_font_m2icon_7.o \
./Drivers/fntsrc/u8g_font_m2icon_9.o \
./Drivers/fntsrc/u8g_font_micro.o \
./Drivers/fntsrc/u8g_font_ncenb08.o \
./Drivers/fntsrc/u8g_font_ncenb08r.o \
./Drivers/fntsrc/u8g_font_ncenb10.o \
./Drivers/fntsrc/u8g_font_ncenb10r.o \
./Drivers/fntsrc/u8g_font_ncenb12.o \
./Drivers/fntsrc/u8g_font_ncenb12r.o \
./Drivers/fntsrc/u8g_font_ncenb14.o \
./Drivers/fntsrc/u8g_font_ncenb14r.o \
./Drivers/fntsrc/u8g_font_ncenb18.o \
./Drivers/fntsrc/u8g_font_ncenb18r.o \
./Drivers/fntsrc/u8g_font_ncenb24.o \
./Drivers/fntsrc/u8g_font_ncenb24n.o \
./Drivers/fntsrc/u8g_font_ncenb24r.o \
./Drivers/fntsrc/u8g_font_ncenr08.o \
./Drivers/fntsrc/u8g_font_ncenr08r.o \
./Drivers/fntsrc/u8g_font_ncenr10.o \
./Drivers/fntsrc/u8g_font_ncenr10r.o \
./Drivers/fntsrc/u8g_font_ncenr12.o \
./Drivers/fntsrc/u8g_font_ncenr12r.o \
./Drivers/fntsrc/u8g_font_ncenr14.o \
./Drivers/fntsrc/u8g_font_ncenr14r.o \
./Drivers/fntsrc/u8g_font_ncenr18.o \
./Drivers/fntsrc/u8g_font_ncenr18r.o \
./Drivers/fntsrc/u8g_font_ncenr24.o \
./Drivers/fntsrc/u8g_font_ncenr24n.o \
./Drivers/fntsrc/u8g_font_ncenr24r.o \
./Drivers/fntsrc/u8g_font_orgv01.o \
./Drivers/fntsrc/u8g_font_orgv01n.o \
./Drivers/fntsrc/u8g_font_orgv01r.o \
./Drivers/fntsrc/u8g_font_osb18.o \
./Drivers/fntsrc/u8g_font_osb18n.o \
./Drivers/fntsrc/u8g_font_osb18r.o \
./Drivers/fntsrc/u8g_font_osb21.o \
./Drivers/fntsrc/u8g_font_osb21n.o \
./Drivers/fntsrc/u8g_font_osb21r.o \
./Drivers/fntsrc/u8g_font_osb26.o \
./Drivers/fntsrc/u8g_font_osb26n.o \
./Drivers/fntsrc/u8g_font_osb26r.o \
./Drivers/fntsrc/u8g_font_osb29.o \
./Drivers/fntsrc/u8g_font_osb29n.o \
./Drivers/fntsrc/u8g_font_osb29r.o \
./Drivers/fntsrc/u8g_font_osb35.o \
./Drivers/fntsrc/u8g_font_osb35n.o \
./Drivers/fntsrc/u8g_font_osb35r.o \
./Drivers/fntsrc/u8g_font_osr18.o \
./Drivers/fntsrc/u8g_font_osr18n.o \
./Drivers/fntsrc/u8g_font_osr18r.o \
./Drivers/fntsrc/u8g_font_osr21.o \
./Drivers/fntsrc/u8g_font_osr21n.o \
./Drivers/fntsrc/u8g_font_osr21r.o \
./Drivers/fntsrc/u8g_font_osr26.o \
./Drivers/fntsrc/u8g_font_osr26n.o \
./Drivers/fntsrc/u8g_font_osr26r.o \
./Drivers/fntsrc/u8g_font_osr29.o \
./Drivers/fntsrc/u8g_font_osr29n.o \
./Drivers/fntsrc/u8g_font_osr29r.o \
./Drivers/fntsrc/u8g_font_osr35.o \
./Drivers/fntsrc/u8g_font_osr35n.o \
./Drivers/fntsrc/u8g_font_osr35r.o \
./Drivers/fntsrc/u8g_font_p01type.o \
./Drivers/fntsrc/u8g_font_p01typen.o \
./Drivers/fntsrc/u8g_font_p01typer.o \
./Drivers/fntsrc/u8g_font_pixelle_micro.o \
./Drivers/fntsrc/u8g_font_pixelle_micron.o \
./Drivers/fntsrc/u8g_font_pixelle_micror.o \
./Drivers/fntsrc/u8g_font_profont10.o \
./Drivers/fntsrc/u8g_font_profont10r.o \
./Drivers/fntsrc/u8g_font_profont11.o \
./Drivers/fntsrc/u8g_font_profont11r.o \
./Drivers/fntsrc/u8g_font_profont12.o \
./Drivers/fntsrc/u8g_font_profont12r.o \
./Drivers/fntsrc/u8g_font_profont15.o \
./Drivers/fntsrc/u8g_font_profont15r.o \
./Drivers/fntsrc/u8g_font_profont17.o \
./Drivers/fntsrc/u8g_font_profont17r.o \
./Drivers/fntsrc/u8g_font_profont22.o \
./Drivers/fntsrc/u8g_font_profont22r.o \
./Drivers/fntsrc/u8g_font_profont29.o \
./Drivers/fntsrc/u8g_font_profont29r.o \
./Drivers/fntsrc/u8g_font_robot_de_niro.o \
./Drivers/fntsrc/u8g_font_robot_de_niron.o \
./Drivers/fntsrc/u8g_font_robot_de_niror.o \
./Drivers/fntsrc/u8g_font_symb08.o \
./Drivers/fntsrc/u8g_font_symb08r.o \
./Drivers/fntsrc/u8g_font_symb10.o \
./Drivers/fntsrc/u8g_font_symb10r.o \
./Drivers/fntsrc/u8g_font_symb12.o \
./Drivers/fntsrc/u8g_font_symb12r.o \
./Drivers/fntsrc/u8g_font_symb14.o \
./Drivers/fntsrc/u8g_font_symb14r.o \
./Drivers/fntsrc/u8g_font_symb18.o \
./Drivers/fntsrc/u8g_font_symb18r.o \
./Drivers/fntsrc/u8g_font_symb24.o \
./Drivers/fntsrc/u8g_font_symb24r.o \
./Drivers/fntsrc/u8g_font_timb08.o \
./Drivers/fntsrc/u8g_font_timb08r.o \
./Drivers/fntsrc/u8g_font_timb10.o \
./Drivers/fntsrc/u8g_font_timb10r.o \
./Drivers/fntsrc/u8g_font_timb12.o \
./Drivers/fntsrc/u8g_font_timb12r.o \
./Drivers/fntsrc/u8g_font_timb14.o \
./Drivers/fntsrc/u8g_font_timb14r.o \
./Drivers/fntsrc/u8g_font_timb18.o \
./Drivers/fntsrc/u8g_font_timb18r.o \
./Drivers/fntsrc/u8g_font_timb24.o \
./Drivers/fntsrc/u8g_font_timb24n.o \
./Drivers/fntsrc/u8g_font_timb24r.o \
./Drivers/fntsrc/u8g_font_timr08.o \
./Drivers/fntsrc/u8g_font_timr08r.o \
./Drivers/fntsrc/u8g_font_timr10.o \
./Drivers/fntsrc/u8g_font_timr10r.o \
./Drivers/fntsrc/u8g_font_timr12.o \
./Drivers/fntsrc/u8g_font_timr12r.o \
./Drivers/fntsrc/u8g_font_timr14.o \
./Drivers/fntsrc/u8g_font_timr14r.o \
./Drivers/fntsrc/u8g_font_timr18.o \
./Drivers/fntsrc/u8g_font_timr18r.o \
./Drivers/fntsrc/u8g_font_timr24.o \
./Drivers/fntsrc/u8g_font_timr24n.o \
./Drivers/fntsrc/u8g_font_timr24r.o \
./Drivers/fntsrc/u8g_font_tpss.o \
./Drivers/fntsrc/u8g_font_tpssb.o \
./Drivers/fntsrc/u8g_font_tpssbn.o \
./Drivers/fntsrc/u8g_font_tpssbr.o \
./Drivers/fntsrc/u8g_font_tpssn.o \
./Drivers/fntsrc/u8g_font_tpssr.o \
./Drivers/fntsrc/u8g_font_trixel_square.o \
./Drivers/fntsrc/u8g_font_trixel_squaren.o \
./Drivers/fntsrc/u8g_font_trixel_squarer.o \
./Drivers/fntsrc/u8g_font_u8glib_4.o \
./Drivers/fntsrc/u8g_font_u8glib_4r.o \
./Drivers/fntsrc/u8g_font_unifont.o \
./Drivers/fntsrc/u8g_font_unifont_0_8.o \
./Drivers/fntsrc/u8g_font_unifont_12_13.o \
./Drivers/fntsrc/u8g_font_unifont_18_19.o \
./Drivers/fntsrc/u8g_font_unifont_2_3.o \
./Drivers/fntsrc/u8g_font_unifont_4_5.o \
./Drivers/fntsrc/u8g_font_unifont_67_75.o \
./Drivers/fntsrc/u8g_font_unifont_72_73.o \
./Drivers/fntsrc/u8g_font_unifont_75r.o \
./Drivers/fntsrc/u8g_font_unifont_76.o \
./Drivers/fntsrc/u8g_font_unifont_77.o \
./Drivers/fntsrc/u8g_font_unifont_78_79.o \
./Drivers/fntsrc/u8g_font_unifont_86.o \
./Drivers/fntsrc/u8g_font_unifont_8_9.o \
./Drivers/fntsrc/u8g_font_unifontr.o 

C_DEPS += \
./Drivers/fntsrc/u8g_font_04b_03.d \
./Drivers/fntsrc/u8g_font_04b_03b.d \
./Drivers/fntsrc/u8g_font_04b_03bn.d \
./Drivers/fntsrc/u8g_font_04b_03br.d \
./Drivers/fntsrc/u8g_font_04b_03n.d \
./Drivers/fntsrc/u8g_font_04b_03r.d \
./Drivers/fntsrc/u8g_font_04b_24.d \
./Drivers/fntsrc/u8g_font_04b_24n.d \
./Drivers/fntsrc/u8g_font_04b_24r.d \
./Drivers/fntsrc/u8g_font_10x20.d \
./Drivers/fntsrc/u8g_font_10x20_67_75.d \
./Drivers/fntsrc/u8g_font_10x20_75r.d \
./Drivers/fntsrc/u8g_font_10x20_78_79.d \
./Drivers/fntsrc/u8g_font_10x20r.d \
./Drivers/fntsrc/u8g_font_4x6.d \
./Drivers/fntsrc/u8g_font_4x6r.d \
./Drivers/fntsrc/u8g_font_5x7.d \
./Drivers/fntsrc/u8g_font_5x7r.d \
./Drivers/fntsrc/u8g_font_5x8.d \
./Drivers/fntsrc/u8g_font_5x8r.d \
./Drivers/fntsrc/u8g_font_6x10.d \
./Drivers/fntsrc/u8g_font_6x10r.d \
./Drivers/fntsrc/u8g_font_6x12.d \
./Drivers/fntsrc/u8g_font_6x12_67_75.d \
./Drivers/fntsrc/u8g_font_6x12_75r.d \
./Drivers/fntsrc/u8g_font_6x12_78_79.d \
./Drivers/fntsrc/u8g_font_6x12r.d \
./Drivers/fntsrc/u8g_font_6x13.d \
./Drivers/fntsrc/u8g_font_6x13B.d \
./Drivers/fntsrc/u8g_font_6x13Br.d \
./Drivers/fntsrc/u8g_font_6x13O.d \
./Drivers/fntsrc/u8g_font_6x13Or.d \
./Drivers/fntsrc/u8g_font_6x13_67_75.d \
./Drivers/fntsrc/u8g_font_6x13_75r.d \
./Drivers/fntsrc/u8g_font_6x13_78_79.d \
./Drivers/fntsrc/u8g_font_6x13r.d \
./Drivers/fntsrc/u8g_font_7x13.d \
./Drivers/fntsrc/u8g_font_7x13B.d \
./Drivers/fntsrc/u8g_font_7x13Br.d \
./Drivers/fntsrc/u8g_font_7x13O.d \
./Drivers/fntsrc/u8g_font_7x13Or.d \
./Drivers/fntsrc/u8g_font_7x13_67_75.d \
./Drivers/fntsrc/u8g_font_7x13_75r.d \
./Drivers/fntsrc/u8g_font_7x13r.d \
./Drivers/fntsrc/u8g_font_7x14.d \
./Drivers/fntsrc/u8g_font_7x14B.d \
./Drivers/fntsrc/u8g_font_7x14Br.d \
./Drivers/fntsrc/u8g_font_7x14r.d \
./Drivers/fntsrc/u8g_font_8x13.d \
./Drivers/fntsrc/u8g_font_8x13B.d \
./Drivers/fntsrc/u8g_font_8x13Br.d \
./Drivers/fntsrc/u8g_font_8x13O.d \
./Drivers/fntsrc/u8g_font_8x13Or.d \
./Drivers/fntsrc/u8g_font_8x13_67_75.d \
./Drivers/fntsrc/u8g_font_8x13_75r.d \
./Drivers/fntsrc/u8g_font_8x13r.d \
./Drivers/fntsrc/u8g_font_9x15.d \
./Drivers/fntsrc/u8g_font_9x15B.d \
./Drivers/fntsrc/u8g_font_9x15Br.d \
./Drivers/fntsrc/u8g_font_9x15_67_75.d \
./Drivers/fntsrc/u8g_font_9x15_75r.d \
./Drivers/fntsrc/u8g_font_9x15_78_79.d \
./Drivers/fntsrc/u8g_font_9x15r.d \
./Drivers/fntsrc/u8g_font_9x18.d \
./Drivers/fntsrc/u8g_font_9x18B.d \
./Drivers/fntsrc/u8g_font_9x18Br.d \
./Drivers/fntsrc/u8g_font_9x18_67_75.d \
./Drivers/fntsrc/u8g_font_9x18_75r.d \
./Drivers/fntsrc/u8g_font_9x18_78_79.d \
./Drivers/fntsrc/u8g_font_9x18r.d \
./Drivers/fntsrc/u8g_font_baby.d \
./Drivers/fntsrc/u8g_font_babyn.d \
./Drivers/fntsrc/u8g_font_babyr.d \
./Drivers/fntsrc/u8g_font_blipfest_07.d \
./Drivers/fntsrc/u8g_font_blipfest_07n.d \
./Drivers/fntsrc/u8g_font_blipfest_07r.d \
./Drivers/fntsrc/u8g_font_chikita.d \
./Drivers/fntsrc/u8g_font_chikitan.d \
./Drivers/fntsrc/u8g_font_chikitar.d \
./Drivers/fntsrc/u8g_font_courb08.d \
./Drivers/fntsrc/u8g_font_courb08r.d \
./Drivers/fntsrc/u8g_font_courb10.d \
./Drivers/fntsrc/u8g_font_courb10r.d \
./Drivers/fntsrc/u8g_font_courb12.d \
./Drivers/fntsrc/u8g_font_courb12r.d \
./Drivers/fntsrc/u8g_font_courb14.d \
./Drivers/fntsrc/u8g_font_courb14r.d \
./Drivers/fntsrc/u8g_font_courb18.d \
./Drivers/fntsrc/u8g_font_courb18r.d \
./Drivers/fntsrc/u8g_font_courb24.d \
./Drivers/fntsrc/u8g_font_courb24r.d \
./Drivers/fntsrc/u8g_font_courb4n.d \
./Drivers/fntsrc/u8g_font_courr08.d \
./Drivers/fntsrc/u8g_font_courr08r.d \
./Drivers/fntsrc/u8g_font_courr10.d \
./Drivers/fntsrc/u8g_font_courr10r.d \
./Drivers/fntsrc/u8g_font_courr12.d \
./Drivers/fntsrc/u8g_font_courr12r.d \
./Drivers/fntsrc/u8g_font_courr14.d \
./Drivers/fntsrc/u8g_font_courr14r.d \
./Drivers/fntsrc/u8g_font_courr18.d \
./Drivers/fntsrc/u8g_font_courr18r.d \
./Drivers/fntsrc/u8g_font_courr24.d \
./Drivers/fntsrc/u8g_font_courr24n.d \
./Drivers/fntsrc/u8g_font_courr24r.d \
./Drivers/fntsrc/u8g_font_cu12.d \
./Drivers/fntsrc/u8g_font_cu12_67_75.d \
./Drivers/fntsrc/u8g_font_cu12_75r.d \
./Drivers/fntsrc/u8g_font_cursor.d \
./Drivers/fntsrc/u8g_font_cursorr.d \
./Drivers/fntsrc/u8g_font_fixed_v0.d \
./Drivers/fntsrc/u8g_font_fixed_v0n.d \
./Drivers/fntsrc/u8g_font_fixed_v0r.d \
./Drivers/fntsrc/u8g_font_freedoomr10r.d \
./Drivers/fntsrc/u8g_font_freedoomr25n.d \
./Drivers/fntsrc/u8g_font_fub11.d \
./Drivers/fntsrc/u8g_font_fub11n.d \
./Drivers/fntsrc/u8g_font_fub11r.d \
./Drivers/fntsrc/u8g_font_fub14.d \
./Drivers/fntsrc/u8g_font_fub14n.d \
./Drivers/fntsrc/u8g_font_fub14r.d \
./Drivers/fntsrc/u8g_font_fub17.d \
./Drivers/fntsrc/u8g_font_fub17n.d \
./Drivers/fntsrc/u8g_font_fub17r.d \
./Drivers/fntsrc/u8g_font_fub20.d \
./Drivers/fntsrc/u8g_font_fub20n.d \
./Drivers/fntsrc/u8g_font_fub20r.d \
./Drivers/fntsrc/u8g_font_fub25.d \
./Drivers/fntsrc/u8g_font_fub25n.d \
./Drivers/fntsrc/u8g_font_fub25r.d \
./Drivers/fntsrc/u8g_font_fub30.d \
./Drivers/fntsrc/u8g_font_fub30n.d \
./Drivers/fntsrc/u8g_font_fub30r.d \
./Drivers/fntsrc/u8g_font_fub35n.d \
./Drivers/fntsrc/u8g_font_fub42n.d \
./Drivers/fntsrc/u8g_font_fub49n.d \
./Drivers/fntsrc/u8g_font_fur11.d \
./Drivers/fntsrc/u8g_font_fur11n.d \
./Drivers/fntsrc/u8g_font_fur11r.d \
./Drivers/fntsrc/u8g_font_fur14.d \
./Drivers/fntsrc/u8g_font_fur14n.d \
./Drivers/fntsrc/u8g_font_fur14r.d \
./Drivers/fntsrc/u8g_font_fur17.d \
./Drivers/fntsrc/u8g_font_fur17n.d \
./Drivers/fntsrc/u8g_font_fur17r.d \
./Drivers/fntsrc/u8g_font_fur20.d \
./Drivers/fntsrc/u8g_font_fur20n.d \
./Drivers/fntsrc/u8g_font_fur20r.d \
./Drivers/fntsrc/u8g_font_fur25.d \
./Drivers/fntsrc/u8g_font_fur25n.d \
./Drivers/fntsrc/u8g_font_fur25r.d \
./Drivers/fntsrc/u8g_font_fur30.d \
./Drivers/fntsrc/u8g_font_fur30n.d \
./Drivers/fntsrc/u8g_font_fur30r.d \
./Drivers/fntsrc/u8g_font_fur35n.d \
./Drivers/fntsrc/u8g_font_fur42n.d \
./Drivers/fntsrc/u8g_font_fur49n.d \
./Drivers/fntsrc/u8g_font_gdb11.d \
./Drivers/fntsrc/u8g_font_gdb11n.d \
./Drivers/fntsrc/u8g_font_gdb11r.d \
./Drivers/fntsrc/u8g_font_gdb12.d \
./Drivers/fntsrc/u8g_font_gdb12n.d \
./Drivers/fntsrc/u8g_font_gdb12r.d \
./Drivers/fntsrc/u8g_font_gdb14.d \
./Drivers/fntsrc/u8g_font_gdb14n.d \
./Drivers/fntsrc/u8g_font_gdb14r.d \
./Drivers/fntsrc/u8g_font_gdb17.d \
./Drivers/fntsrc/u8g_font_gdb17n.d \
./Drivers/fntsrc/u8g_font_gdb17r.d \
./Drivers/fntsrc/u8g_font_gdb20.d \
./Drivers/fntsrc/u8g_font_gdb20n.d \
./Drivers/fntsrc/u8g_font_gdb20r.d \
./Drivers/fntsrc/u8g_font_gdb25.d \
./Drivers/fntsrc/u8g_font_gdb25n.d \
./Drivers/fntsrc/u8g_font_gdb25r.d \
./Drivers/fntsrc/u8g_font_gdb30.d \
./Drivers/fntsrc/u8g_font_gdb30n.d \
./Drivers/fntsrc/u8g_font_gdb30r.d \
./Drivers/fntsrc/u8g_font_gdr10.d \
./Drivers/fntsrc/u8g_font_gdr10n.d \
./Drivers/fntsrc/u8g_font_gdr10r.d \
./Drivers/fntsrc/u8g_font_gdr11.d \
./Drivers/fntsrc/u8g_font_gdr11n.d \
./Drivers/fntsrc/u8g_font_gdr11r.d \
./Drivers/fntsrc/u8g_font_gdr12.d \
./Drivers/fntsrc/u8g_font_gdr12n.d \
./Drivers/fntsrc/u8g_font_gdr12r.d \
./Drivers/fntsrc/u8g_font_gdr14.d \
./Drivers/fntsrc/u8g_font_gdr14n.d \
./Drivers/fntsrc/u8g_font_gdr14r.d \
./Drivers/fntsrc/u8g_font_gdr17.d \
./Drivers/fntsrc/u8g_font_gdr17n.d \
./Drivers/fntsrc/u8g_font_gdr17r.d \
./Drivers/fntsrc/u8g_font_gdr20.d \
./Drivers/fntsrc/u8g_font_gdr20n.d \
./Drivers/fntsrc/u8g_font_gdr20r.d \
./Drivers/fntsrc/u8g_font_gdr25.d \
./Drivers/fntsrc/u8g_font_gdr25n.d \
./Drivers/fntsrc/u8g_font_gdr25r.d \
./Drivers/fntsrc/u8g_font_gdr30.d \
./Drivers/fntsrc/u8g_font_gdr30n.d \
./Drivers/fntsrc/u8g_font_gdr30r.d \
./Drivers/fntsrc/u8g_font_gdr9.d \
./Drivers/fntsrc/u8g_font_gdr9n.d \
./Drivers/fntsrc/u8g_font_gdr9r.d \
./Drivers/fntsrc/u8g_font_helvb08.d \
./Drivers/fntsrc/u8g_font_helvb08n.d \
./Drivers/fntsrc/u8g_font_helvb08r.d \
./Drivers/fntsrc/u8g_font_helvb10.d \
./Drivers/fntsrc/u8g_font_helvb10n.d \
./Drivers/fntsrc/u8g_font_helvb10r.d \
./Drivers/fntsrc/u8g_font_helvb12.d \
./Drivers/fntsrc/u8g_font_helvb12n.d \
./Drivers/fntsrc/u8g_font_helvb12r.d \
./Drivers/fntsrc/u8g_font_helvb14.d \
./Drivers/fntsrc/u8g_font_helvb14n.d \
./Drivers/fntsrc/u8g_font_helvb14r.d \
./Drivers/fntsrc/u8g_font_helvb18.d \
./Drivers/fntsrc/u8g_font_helvb18n.d \
./Drivers/fntsrc/u8g_font_helvb18r.d \
./Drivers/fntsrc/u8g_font_helvb24.d \
./Drivers/fntsrc/u8g_font_helvb24n.d \
./Drivers/fntsrc/u8g_font_helvb24r.d \
./Drivers/fntsrc/u8g_font_helvr08.d \
./Drivers/fntsrc/u8g_font_helvr08r.d \
./Drivers/fntsrc/u8g_font_helvr10.d \
./Drivers/fntsrc/u8g_font_helvr10r.d \
./Drivers/fntsrc/u8g_font_helvr12.d \
./Drivers/fntsrc/u8g_font_helvr12r.d \
./Drivers/fntsrc/u8g_font_helvr14.d \
./Drivers/fntsrc/u8g_font_helvr14r.d \
./Drivers/fntsrc/u8g_font_helvr18.d \
./Drivers/fntsrc/u8g_font_helvr18r.d \
./Drivers/fntsrc/u8g_font_helvr24.d \
./Drivers/fntsrc/u8g_font_helvr24n.d \
./Drivers/fntsrc/u8g_font_helvr24r.d \
./Drivers/fntsrc/u8g_font_lucasfont_alternate.d \
./Drivers/fntsrc/u8g_font_lucasfont_alternaten.d \
./Drivers/fntsrc/u8g_font_lucasfont_alternater.d \
./Drivers/fntsrc/u8g_font_m2icon_5.d \
./Drivers/fntsrc/u8g_font_m2icon_7.d \
./Drivers/fntsrc/u8g_font_m2icon_9.d \
./Drivers/fntsrc/u8g_font_micro.d \
./Drivers/fntsrc/u8g_font_ncenb08.d \
./Drivers/fntsrc/u8g_font_ncenb08r.d \
./Drivers/fntsrc/u8g_font_ncenb10.d \
./Drivers/fntsrc/u8g_font_ncenb10r.d \
./Drivers/fntsrc/u8g_font_ncenb12.d \
./Drivers/fntsrc/u8g_font_ncenb12r.d \
./Drivers/fntsrc/u8g_font_ncenb14.d \
./Drivers/fntsrc/u8g_font_ncenb14r.d \
./Drivers/fntsrc/u8g_font_ncenb18.d \
./Drivers/fntsrc/u8g_font_ncenb18r.d \
./Drivers/fntsrc/u8g_font_ncenb24.d \
./Drivers/fntsrc/u8g_font_ncenb24n.d \
./Drivers/fntsrc/u8g_font_ncenb24r.d \
./Drivers/fntsrc/u8g_font_ncenr08.d \
./Drivers/fntsrc/u8g_font_ncenr08r.d \
./Drivers/fntsrc/u8g_font_ncenr10.d \
./Drivers/fntsrc/u8g_font_ncenr10r.d \
./Drivers/fntsrc/u8g_font_ncenr12.d \
./Drivers/fntsrc/u8g_font_ncenr12r.d \
./Drivers/fntsrc/u8g_font_ncenr14.d \
./Drivers/fntsrc/u8g_font_ncenr14r.d \
./Drivers/fntsrc/u8g_font_ncenr18.d \
./Drivers/fntsrc/u8g_font_ncenr18r.d \
./Drivers/fntsrc/u8g_font_ncenr24.d \
./Drivers/fntsrc/u8g_font_ncenr24n.d \
./Drivers/fntsrc/u8g_font_ncenr24r.d \
./Drivers/fntsrc/u8g_font_orgv01.d \
./Drivers/fntsrc/u8g_font_orgv01n.d \
./Drivers/fntsrc/u8g_font_orgv01r.d \
./Drivers/fntsrc/u8g_font_osb18.d \
./Drivers/fntsrc/u8g_font_osb18n.d \
./Drivers/fntsrc/u8g_font_osb18r.d \
./Drivers/fntsrc/u8g_font_osb21.d \
./Drivers/fntsrc/u8g_font_osb21n.d \
./Drivers/fntsrc/u8g_font_osb21r.d \
./Drivers/fntsrc/u8g_font_osb26.d \
./Drivers/fntsrc/u8g_font_osb26n.d \
./Drivers/fntsrc/u8g_font_osb26r.d \
./Drivers/fntsrc/u8g_font_osb29.d \
./Drivers/fntsrc/u8g_font_osb29n.d \
./Drivers/fntsrc/u8g_font_osb29r.d \
./Drivers/fntsrc/u8g_font_osb35.d \
./Drivers/fntsrc/u8g_font_osb35n.d \
./Drivers/fntsrc/u8g_font_osb35r.d \
./Drivers/fntsrc/u8g_font_osr18.d \
./Drivers/fntsrc/u8g_font_osr18n.d \
./Drivers/fntsrc/u8g_font_osr18r.d \
./Drivers/fntsrc/u8g_font_osr21.d \
./Drivers/fntsrc/u8g_font_osr21n.d \
./Drivers/fntsrc/u8g_font_osr21r.d \
./Drivers/fntsrc/u8g_font_osr26.d \
./Drivers/fntsrc/u8g_font_osr26n.d \
./Drivers/fntsrc/u8g_font_osr26r.d \
./Drivers/fntsrc/u8g_font_osr29.d \
./Drivers/fntsrc/u8g_font_osr29n.d \
./Drivers/fntsrc/u8g_font_osr29r.d \
./Drivers/fntsrc/u8g_font_osr35.d \
./Drivers/fntsrc/u8g_font_osr35n.d \
./Drivers/fntsrc/u8g_font_osr35r.d \
./Drivers/fntsrc/u8g_font_p01type.d \
./Drivers/fntsrc/u8g_font_p01typen.d \
./Drivers/fntsrc/u8g_font_p01typer.d \
./Drivers/fntsrc/u8g_font_pixelle_micro.d \
./Drivers/fntsrc/u8g_font_pixelle_micron.d \
./Drivers/fntsrc/u8g_font_pixelle_micror.d \
./Drivers/fntsrc/u8g_font_profont10.d \
./Drivers/fntsrc/u8g_font_profont10r.d \
./Drivers/fntsrc/u8g_font_profont11.d \
./Drivers/fntsrc/u8g_font_profont11r.d \
./Drivers/fntsrc/u8g_font_profont12.d \
./Drivers/fntsrc/u8g_font_profont12r.d \
./Drivers/fntsrc/u8g_font_profont15.d \
./Drivers/fntsrc/u8g_font_profont15r.d \
./Drivers/fntsrc/u8g_font_profont17.d \
./Drivers/fntsrc/u8g_font_profont17r.d \
./Drivers/fntsrc/u8g_font_profont22.d \
./Drivers/fntsrc/u8g_font_profont22r.d \
./Drivers/fntsrc/u8g_font_profont29.d \
./Drivers/fntsrc/u8g_font_profont29r.d \
./Drivers/fntsrc/u8g_font_robot_de_niro.d \
./Drivers/fntsrc/u8g_font_robot_de_niron.d \
./Drivers/fntsrc/u8g_font_robot_de_niror.d \
./Drivers/fntsrc/u8g_font_symb08.d \
./Drivers/fntsrc/u8g_font_symb08r.d \
./Drivers/fntsrc/u8g_font_symb10.d \
./Drivers/fntsrc/u8g_font_symb10r.d \
./Drivers/fntsrc/u8g_font_symb12.d \
./Drivers/fntsrc/u8g_font_symb12r.d \
./Drivers/fntsrc/u8g_font_symb14.d \
./Drivers/fntsrc/u8g_font_symb14r.d \
./Drivers/fntsrc/u8g_font_symb18.d \
./Drivers/fntsrc/u8g_font_symb18r.d \
./Drivers/fntsrc/u8g_font_symb24.d \
./Drivers/fntsrc/u8g_font_symb24r.d \
./Drivers/fntsrc/u8g_font_timb08.d \
./Drivers/fntsrc/u8g_font_timb08r.d \
./Drivers/fntsrc/u8g_font_timb10.d \
./Drivers/fntsrc/u8g_font_timb10r.d \
./Drivers/fntsrc/u8g_font_timb12.d \
./Drivers/fntsrc/u8g_font_timb12r.d \
./Drivers/fntsrc/u8g_font_timb14.d \
./Drivers/fntsrc/u8g_font_timb14r.d \
./Drivers/fntsrc/u8g_font_timb18.d \
./Drivers/fntsrc/u8g_font_timb18r.d \
./Drivers/fntsrc/u8g_font_timb24.d \
./Drivers/fntsrc/u8g_font_timb24n.d \
./Drivers/fntsrc/u8g_font_timb24r.d \
./Drivers/fntsrc/u8g_font_timr08.d \
./Drivers/fntsrc/u8g_font_timr08r.d \
./Drivers/fntsrc/u8g_font_timr10.d \
./Drivers/fntsrc/u8g_font_timr10r.d \
./Drivers/fntsrc/u8g_font_timr12.d \
./Drivers/fntsrc/u8g_font_timr12r.d \
./Drivers/fntsrc/u8g_font_timr14.d \
./Drivers/fntsrc/u8g_font_timr14r.d \
./Drivers/fntsrc/u8g_font_timr18.d \
./Drivers/fntsrc/u8g_font_timr18r.d \
./Drivers/fntsrc/u8g_font_timr24.d \
./Drivers/fntsrc/u8g_font_timr24n.d \
./Drivers/fntsrc/u8g_font_timr24r.d \
./Drivers/fntsrc/u8g_font_tpss.d \
./Drivers/fntsrc/u8g_font_tpssb.d \
./Drivers/fntsrc/u8g_font_tpssbn.d \
./Drivers/fntsrc/u8g_font_tpssbr.d \
./Drivers/fntsrc/u8g_font_tpssn.d \
./Drivers/fntsrc/u8g_font_tpssr.d \
./Drivers/fntsrc/u8g_font_trixel_square.d \
./Drivers/fntsrc/u8g_font_trixel_squaren.d \
./Drivers/fntsrc/u8g_font_trixel_squarer.d \
./Drivers/fntsrc/u8g_font_u8glib_4.d \
./Drivers/fntsrc/u8g_font_u8glib_4r.d \
./Drivers/fntsrc/u8g_font_unifont.d \
./Drivers/fntsrc/u8g_font_unifont_0_8.d \
./Drivers/fntsrc/u8g_font_unifont_12_13.d \
./Drivers/fntsrc/u8g_font_unifont_18_19.d \
./Drivers/fntsrc/u8g_font_unifont_2_3.d \
./Drivers/fntsrc/u8g_font_unifont_4_5.d \
./Drivers/fntsrc/u8g_font_unifont_67_75.d \
./Drivers/fntsrc/u8g_font_unifont_72_73.d \
./Drivers/fntsrc/u8g_font_unifont_75r.d \
./Drivers/fntsrc/u8g_font_unifont_76.d \
./Drivers/fntsrc/u8g_font_unifont_77.d \
./Drivers/fntsrc/u8g_font_unifont_78_79.d \
./Drivers/fntsrc/u8g_font_unifont_86.d \
./Drivers/fntsrc/u8g_font_unifont_8_9.d \
./Drivers/fntsrc/u8g_font_unifontr.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/fntsrc/%.o Drivers/fntsrc/%.su: ../Drivers/fntsrc/%.c Drivers/fntsrc/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../Core/Inc -I"C:/Users/Dimas/Documents/SVN_MCU/STM32/Workspace_STM32CubeIDE/TP1_RTOS_OLED_ADC_4_Channel/Drivers/u8glib" -I"C:/Users/Dimas/Documents/SVN_MCU/STM32/Workspace_STM32CubeIDE/TP1_RTOS_OLED_ADC_4_Channel/Drivers/fntsrc" -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-Drivers-2f-fntsrc

clean-Drivers-2f-fntsrc:
	-$(RM) ./Drivers/fntsrc/u8g_font_04b_03.d ./Drivers/fntsrc/u8g_font_04b_03.o ./Drivers/fntsrc/u8g_font_04b_03.su ./Drivers/fntsrc/u8g_font_04b_03b.d ./Drivers/fntsrc/u8g_font_04b_03b.o ./Drivers/fntsrc/u8g_font_04b_03b.su ./Drivers/fntsrc/u8g_font_04b_03bn.d ./Drivers/fntsrc/u8g_font_04b_03bn.o ./Drivers/fntsrc/u8g_font_04b_03bn.su ./Drivers/fntsrc/u8g_font_04b_03br.d ./Drivers/fntsrc/u8g_font_04b_03br.o ./Drivers/fntsrc/u8g_font_04b_03br.su ./Drivers/fntsrc/u8g_font_04b_03n.d ./Drivers/fntsrc/u8g_font_04b_03n.o ./Drivers/fntsrc/u8g_font_04b_03n.su ./Drivers/fntsrc/u8g_font_04b_03r.d ./Drivers/fntsrc/u8g_font_04b_03r.o ./Drivers/fntsrc/u8g_font_04b_03r.su ./Drivers/fntsrc/u8g_font_04b_24.d ./Drivers/fntsrc/u8g_font_04b_24.o ./Drivers/fntsrc/u8g_font_04b_24.su ./Drivers/fntsrc/u8g_font_04b_24n.d ./Drivers/fntsrc/u8g_font_04b_24n.o ./Drivers/fntsrc/u8g_font_04b_24n.su ./Drivers/fntsrc/u8g_font_04b_24r.d ./Drivers/fntsrc/u8g_font_04b_24r.o ./Drivers/fntsrc/u8g_font_04b_24r.su ./Drivers/fntsrc/u8g_font_10x20.d ./Drivers/fntsrc/u8g_font_10x20.o ./Drivers/fntsrc/u8g_font_10x20.su ./Drivers/fntsrc/u8g_font_10x20_67_75.d ./Drivers/fntsrc/u8g_font_10x20_67_75.o ./Drivers/fntsrc/u8g_font_10x20_67_75.su ./Drivers/fntsrc/u8g_font_10x20_75r.d ./Drivers/fntsrc/u8g_font_10x20_75r.o ./Drivers/fntsrc/u8g_font_10x20_75r.su ./Drivers/fntsrc/u8g_font_10x20_78_79.d ./Drivers/fntsrc/u8g_font_10x20_78_79.o ./Drivers/fntsrc/u8g_font_10x20_78_79.su ./Drivers/fntsrc/u8g_font_10x20r.d ./Drivers/fntsrc/u8g_font_10x20r.o ./Drivers/fntsrc/u8g_font_10x20r.su ./Drivers/fntsrc/u8g_font_4x6.d ./Drivers/fntsrc/u8g_font_4x6.o ./Drivers/fntsrc/u8g_font_4x6.su ./Drivers/fntsrc/u8g_font_4x6r.d ./Drivers/fntsrc/u8g_font_4x6r.o ./Drivers/fntsrc/u8g_font_4x6r.su ./Drivers/fntsrc/u8g_font_5x7.d ./Drivers/fntsrc/u8g_font_5x7.o ./Drivers/fntsrc/u8g_font_5x7.su ./Drivers/fntsrc/u8g_font_5x7r.d ./Drivers/fntsrc/u8g_font_5x7r.o ./Drivers/fntsrc/u8g_font_5x7r.su ./Drivers/fntsrc/u8g_font_5x8.d ./Drivers/fntsrc/u8g_font_5x8.o ./Drivers/fntsrc/u8g_font_5x8.su ./Drivers/fntsrc/u8g_font_5x8r.d ./Drivers/fntsrc/u8g_font_5x8r.o ./Drivers/fntsrc/u8g_font_5x8r.su ./Drivers/fntsrc/u8g_font_6x10.d ./Drivers/fntsrc/u8g_font_6x10.o ./Drivers/fntsrc/u8g_font_6x10.su ./Drivers/fntsrc/u8g_font_6x10r.d ./Drivers/fntsrc/u8g_font_6x10r.o ./Drivers/fntsrc/u8g_font_6x10r.su ./Drivers/fntsrc/u8g_font_6x12.d ./Drivers/fntsrc/u8g_font_6x12.o ./Drivers/fntsrc/u8g_font_6x12.su ./Drivers/fntsrc/u8g_font_6x12_67_75.d ./Drivers/fntsrc/u8g_font_6x12_67_75.o ./Drivers/fntsrc/u8g_font_6x12_67_75.su ./Drivers/fntsrc/u8g_font_6x12_75r.d ./Drivers/fntsrc/u8g_font_6x12_75r.o ./Drivers/fntsrc/u8g_font_6x12_75r.su ./Drivers/fntsrc/u8g_font_6x12_78_79.d ./Drivers/fntsrc/u8g_font_6x12_78_79.o ./Drivers/fntsrc/u8g_font_6x12_78_79.su ./Drivers/fntsrc/u8g_font_6x12r.d ./Drivers/fntsrc/u8g_font_6x12r.o ./Drivers/fntsrc/u8g_font_6x12r.su ./Drivers/fntsrc/u8g_font_6x13.d ./Drivers/fntsrc/u8g_font_6x13.o ./Drivers/fntsrc/u8g_font_6x13.su ./Drivers/fntsrc/u8g_font_6x13B.d ./Drivers/fntsrc/u8g_font_6x13B.o ./Drivers/fntsrc/u8g_font_6x13B.su ./Drivers/fntsrc/u8g_font_6x13Br.d ./Drivers/fntsrc/u8g_font_6x13Br.o ./Drivers/fntsrc/u8g_font_6x13Br.su ./Drivers/fntsrc/u8g_font_6x13O.d ./Drivers/fntsrc/u8g_font_6x13O.o ./Drivers/fntsrc/u8g_font_6x13O.su ./Drivers/fntsrc/u8g_font_6x13Or.d ./Drivers/fntsrc/u8g_font_6x13Or.o ./Drivers/fntsrc/u8g_font_6x13Or.su ./Drivers/fntsrc/u8g_font_6x13_67_75.d ./Drivers/fntsrc/u8g_font_6x13_67_75.o ./Drivers/fntsrc/u8g_font_6x13_67_75.su ./Drivers/fntsrc/u8g_font_6x13_75r.d ./Drivers/fntsrc/u8g_font_6x13_75r.o ./Drivers/fntsrc/u8g_font_6x13_75r.su ./Drivers/fntsrc/u8g_font_6x13_78_79.d ./Drivers/fntsrc/u8g_font_6x13_78_79.o ./Drivers/fntsrc/u8g_font_6x13_78_79.su ./Drivers/fntsrc/u8g_font_6x13r.d ./Drivers/fntsrc/u8g_font_6x13r.o ./Drivers/fntsrc/u8g_font_6x13r.su ./Drivers/fntsrc/u8g_font_7x13.d ./Drivers/fntsrc/u8g_font_7x13.o ./Drivers/fntsrc/u8g_font_7x13.su ./Drivers/fntsrc/u8g_font_7x13B.d ./Drivers/fntsrc/u8g_font_7x13B.o ./Drivers/fntsrc/u8g_font_7x13B.su ./Drivers/fntsrc/u8g_font_7x13Br.d ./Drivers/fntsrc/u8g_font_7x13Br.o ./Drivers/fntsrc/u8g_font_7x13Br.su ./Drivers/fntsrc/u8g_font_7x13O.d ./Drivers/fntsrc/u8g_font_7x13O.o ./Drivers/fntsrc/u8g_font_7x13O.su ./Drivers/fntsrc/u8g_font_7x13Or.d ./Drivers/fntsrc/u8g_font_7x13Or.o ./Drivers/fntsrc/u8g_font_7x13Or.su ./Drivers/fntsrc/u8g_font_7x13_67_75.d ./Drivers/fntsrc/u8g_font_7x13_67_75.o ./Drivers/fntsrc/u8g_font_7x13_67_75.su ./Drivers/fntsrc/u8g_font_7x13_75r.d ./Drivers/fntsrc/u8g_font_7x13_75r.o ./Drivers/fntsrc/u8g_font_7x13_75r.su ./Drivers/fntsrc/u8g_font_7x13r.d ./Drivers/fntsrc/u8g_font_7x13r.o ./Drivers/fntsrc/u8g_font_7x13r.su ./Drivers/fntsrc/u8g_font_7x14.d ./Drivers/fntsrc/u8g_font_7x14.o ./Drivers/fntsrc/u8g_font_7x14.su ./Drivers/fntsrc/u8g_font_7x14B.d ./Drivers/fntsrc/u8g_font_7x14B.o ./Drivers/fntsrc/u8g_font_7x14B.su ./Drivers/fntsrc/u8g_font_7x14Br.d ./Drivers/fntsrc/u8g_font_7x14Br.o ./Drivers/fntsrc/u8g_font_7x14Br.su ./Drivers/fntsrc/u8g_font_7x14r.d ./Drivers/fntsrc/u8g_font_7x14r.o ./Drivers/fntsrc/u8g_font_7x14r.su ./Drivers/fntsrc/u8g_font_8x13.d ./Drivers/fntsrc/u8g_font_8x13.o ./Drivers/fntsrc/u8g_font_8x13.su ./Drivers/fntsrc/u8g_font_8x13B.d ./Drivers/fntsrc/u8g_font_8x13B.o ./Drivers/fntsrc/u8g_font_8x13B.su ./Drivers/fntsrc/u8g_font_8x13Br.d ./Drivers/fntsrc/u8g_font_8x13Br.o ./Drivers/fntsrc/u8g_font_8x13Br.su ./Drivers/fntsrc/u8g_font_8x13O.d ./Drivers/fntsrc/u8g_font_8x13O.o ./Drivers/fntsrc/u8g_font_8x13O.su ./Drivers/fntsrc/u8g_font_8x13Or.d ./Drivers/fntsrc/u8g_font_8x13Or.o ./Drivers/fntsrc/u8g_font_8x13Or.su ./Drivers/fntsrc/u8g_font_8x13_67_75.d ./Drivers/fntsrc/u8g_font_8x13_67_75.o ./Drivers/fntsrc/u8g_font_8x13_67_75.su ./Drivers/fntsrc/u8g_font_8x13_75r.d ./Drivers/fntsrc/u8g_font_8x13_75r.o ./Drivers/fntsrc/u8g_font_8x13_75r.su ./Drivers/fntsrc/u8g_font_8x13r.d ./Drivers/fntsrc/u8g_font_8x13r.o ./Drivers/fntsrc/u8g_font_8x13r.su
	-$(RM) ./Drivers/fntsrc/u8g_font_9x15.d ./Drivers/fntsrc/u8g_font_9x15.o ./Drivers/fntsrc/u8g_font_9x15.su ./Drivers/fntsrc/u8g_font_9x15B.d ./Drivers/fntsrc/u8g_font_9x15B.o ./Drivers/fntsrc/u8g_font_9x15B.su ./Drivers/fntsrc/u8g_font_9x15Br.d ./Drivers/fntsrc/u8g_font_9x15Br.o ./Drivers/fntsrc/u8g_font_9x15Br.su ./Drivers/fntsrc/u8g_font_9x15_67_75.d ./Drivers/fntsrc/u8g_font_9x15_67_75.o ./Drivers/fntsrc/u8g_font_9x15_67_75.su ./Drivers/fntsrc/u8g_font_9x15_75r.d ./Drivers/fntsrc/u8g_font_9x15_75r.o ./Drivers/fntsrc/u8g_font_9x15_75r.su ./Drivers/fntsrc/u8g_font_9x15_78_79.d ./Drivers/fntsrc/u8g_font_9x15_78_79.o ./Drivers/fntsrc/u8g_font_9x15_78_79.su ./Drivers/fntsrc/u8g_font_9x15r.d ./Drivers/fntsrc/u8g_font_9x15r.o ./Drivers/fntsrc/u8g_font_9x15r.su ./Drivers/fntsrc/u8g_font_9x18.d ./Drivers/fntsrc/u8g_font_9x18.o ./Drivers/fntsrc/u8g_font_9x18.su ./Drivers/fntsrc/u8g_font_9x18B.d ./Drivers/fntsrc/u8g_font_9x18B.o ./Drivers/fntsrc/u8g_font_9x18B.su ./Drivers/fntsrc/u8g_font_9x18Br.d ./Drivers/fntsrc/u8g_font_9x18Br.o ./Drivers/fntsrc/u8g_font_9x18Br.su ./Drivers/fntsrc/u8g_font_9x18_67_75.d ./Drivers/fntsrc/u8g_font_9x18_67_75.o ./Drivers/fntsrc/u8g_font_9x18_67_75.su ./Drivers/fntsrc/u8g_font_9x18_75r.d ./Drivers/fntsrc/u8g_font_9x18_75r.o ./Drivers/fntsrc/u8g_font_9x18_75r.su ./Drivers/fntsrc/u8g_font_9x18_78_79.d ./Drivers/fntsrc/u8g_font_9x18_78_79.o ./Drivers/fntsrc/u8g_font_9x18_78_79.su ./Drivers/fntsrc/u8g_font_9x18r.d ./Drivers/fntsrc/u8g_font_9x18r.o ./Drivers/fntsrc/u8g_font_9x18r.su ./Drivers/fntsrc/u8g_font_baby.d ./Drivers/fntsrc/u8g_font_baby.o ./Drivers/fntsrc/u8g_font_baby.su ./Drivers/fntsrc/u8g_font_babyn.d ./Drivers/fntsrc/u8g_font_babyn.o ./Drivers/fntsrc/u8g_font_babyn.su ./Drivers/fntsrc/u8g_font_babyr.d ./Drivers/fntsrc/u8g_font_babyr.o ./Drivers/fntsrc/u8g_font_babyr.su ./Drivers/fntsrc/u8g_font_blipfest_07.d ./Drivers/fntsrc/u8g_font_blipfest_07.o ./Drivers/fntsrc/u8g_font_blipfest_07.su ./Drivers/fntsrc/u8g_font_blipfest_07n.d ./Drivers/fntsrc/u8g_font_blipfest_07n.o ./Drivers/fntsrc/u8g_font_blipfest_07n.su ./Drivers/fntsrc/u8g_font_blipfest_07r.d ./Drivers/fntsrc/u8g_font_blipfest_07r.o ./Drivers/fntsrc/u8g_font_blipfest_07r.su ./Drivers/fntsrc/u8g_font_chikita.d ./Drivers/fntsrc/u8g_font_chikita.o ./Drivers/fntsrc/u8g_font_chikita.su ./Drivers/fntsrc/u8g_font_chikitan.d ./Drivers/fntsrc/u8g_font_chikitan.o ./Drivers/fntsrc/u8g_font_chikitan.su ./Drivers/fntsrc/u8g_font_chikitar.d ./Drivers/fntsrc/u8g_font_chikitar.o ./Drivers/fntsrc/u8g_font_chikitar.su ./Drivers/fntsrc/u8g_font_courb08.d ./Drivers/fntsrc/u8g_font_courb08.o ./Drivers/fntsrc/u8g_font_courb08.su ./Drivers/fntsrc/u8g_font_courb08r.d ./Drivers/fntsrc/u8g_font_courb08r.o ./Drivers/fntsrc/u8g_font_courb08r.su ./Drivers/fntsrc/u8g_font_courb10.d ./Drivers/fntsrc/u8g_font_courb10.o ./Drivers/fntsrc/u8g_font_courb10.su ./Drivers/fntsrc/u8g_font_courb10r.d ./Drivers/fntsrc/u8g_font_courb10r.o ./Drivers/fntsrc/u8g_font_courb10r.su ./Drivers/fntsrc/u8g_font_courb12.d ./Drivers/fntsrc/u8g_font_courb12.o ./Drivers/fntsrc/u8g_font_courb12.su ./Drivers/fntsrc/u8g_font_courb12r.d ./Drivers/fntsrc/u8g_font_courb12r.o ./Drivers/fntsrc/u8g_font_courb12r.su ./Drivers/fntsrc/u8g_font_courb14.d ./Drivers/fntsrc/u8g_font_courb14.o ./Drivers/fntsrc/u8g_font_courb14.su ./Drivers/fntsrc/u8g_font_courb14r.d ./Drivers/fntsrc/u8g_font_courb14r.o ./Drivers/fntsrc/u8g_font_courb14r.su ./Drivers/fntsrc/u8g_font_courb18.d ./Drivers/fntsrc/u8g_font_courb18.o ./Drivers/fntsrc/u8g_font_courb18.su ./Drivers/fntsrc/u8g_font_courb18r.d ./Drivers/fntsrc/u8g_font_courb18r.o ./Drivers/fntsrc/u8g_font_courb18r.su ./Drivers/fntsrc/u8g_font_courb24.d ./Drivers/fntsrc/u8g_font_courb24.o ./Drivers/fntsrc/u8g_font_courb24.su ./Drivers/fntsrc/u8g_font_courb24r.d ./Drivers/fntsrc/u8g_font_courb24r.o ./Drivers/fntsrc/u8g_font_courb24r.su ./Drivers/fntsrc/u8g_font_courb4n.d ./Drivers/fntsrc/u8g_font_courb4n.o ./Drivers/fntsrc/u8g_font_courb4n.su ./Drivers/fntsrc/u8g_font_courr08.d ./Drivers/fntsrc/u8g_font_courr08.o ./Drivers/fntsrc/u8g_font_courr08.su ./Drivers/fntsrc/u8g_font_courr08r.d ./Drivers/fntsrc/u8g_font_courr08r.o ./Drivers/fntsrc/u8g_font_courr08r.su ./Drivers/fntsrc/u8g_font_courr10.d ./Drivers/fntsrc/u8g_font_courr10.o ./Drivers/fntsrc/u8g_font_courr10.su ./Drivers/fntsrc/u8g_font_courr10r.d ./Drivers/fntsrc/u8g_font_courr10r.o ./Drivers/fntsrc/u8g_font_courr10r.su ./Drivers/fntsrc/u8g_font_courr12.d ./Drivers/fntsrc/u8g_font_courr12.o ./Drivers/fntsrc/u8g_font_courr12.su ./Drivers/fntsrc/u8g_font_courr12r.d ./Drivers/fntsrc/u8g_font_courr12r.o ./Drivers/fntsrc/u8g_font_courr12r.su ./Drivers/fntsrc/u8g_font_courr14.d ./Drivers/fntsrc/u8g_font_courr14.o ./Drivers/fntsrc/u8g_font_courr14.su ./Drivers/fntsrc/u8g_font_courr14r.d ./Drivers/fntsrc/u8g_font_courr14r.o ./Drivers/fntsrc/u8g_font_courr14r.su ./Drivers/fntsrc/u8g_font_courr18.d ./Drivers/fntsrc/u8g_font_courr18.o ./Drivers/fntsrc/u8g_font_courr18.su ./Drivers/fntsrc/u8g_font_courr18r.d ./Drivers/fntsrc/u8g_font_courr18r.o ./Drivers/fntsrc/u8g_font_courr18r.su ./Drivers/fntsrc/u8g_font_courr24.d ./Drivers/fntsrc/u8g_font_courr24.o ./Drivers/fntsrc/u8g_font_courr24.su ./Drivers/fntsrc/u8g_font_courr24n.d ./Drivers/fntsrc/u8g_font_courr24n.o ./Drivers/fntsrc/u8g_font_courr24n.su ./Drivers/fntsrc/u8g_font_courr24r.d ./Drivers/fntsrc/u8g_font_courr24r.o ./Drivers/fntsrc/u8g_font_courr24r.su ./Drivers/fntsrc/u8g_font_cu12.d ./Drivers/fntsrc/u8g_font_cu12.o ./Drivers/fntsrc/u8g_font_cu12.su ./Drivers/fntsrc/u8g_font_cu12_67_75.d ./Drivers/fntsrc/u8g_font_cu12_67_75.o ./Drivers/fntsrc/u8g_font_cu12_67_75.su ./Drivers/fntsrc/u8g_font_cu12_75r.d ./Drivers/fntsrc/u8g_font_cu12_75r.o ./Drivers/fntsrc/u8g_font_cu12_75r.su ./Drivers/fntsrc/u8g_font_cursor.d ./Drivers/fntsrc/u8g_font_cursor.o ./Drivers/fntsrc/u8g_font_cursor.su ./Drivers/fntsrc/u8g_font_cursorr.d ./Drivers/fntsrc/u8g_font_cursorr.o ./Drivers/fntsrc/u8g_font_cursorr.su ./Drivers/fntsrc/u8g_font_fixed_v0.d
	-$(RM) ./Drivers/fntsrc/u8g_font_fixed_v0.o ./Drivers/fntsrc/u8g_font_fixed_v0.su ./Drivers/fntsrc/u8g_font_fixed_v0n.d ./Drivers/fntsrc/u8g_font_fixed_v0n.o ./Drivers/fntsrc/u8g_font_fixed_v0n.su ./Drivers/fntsrc/u8g_font_fixed_v0r.d ./Drivers/fntsrc/u8g_font_fixed_v0r.o ./Drivers/fntsrc/u8g_font_fixed_v0r.su ./Drivers/fntsrc/u8g_font_freedoomr10r.d ./Drivers/fntsrc/u8g_font_freedoomr10r.o ./Drivers/fntsrc/u8g_font_freedoomr10r.su ./Drivers/fntsrc/u8g_font_freedoomr25n.d ./Drivers/fntsrc/u8g_font_freedoomr25n.o ./Drivers/fntsrc/u8g_font_freedoomr25n.su ./Drivers/fntsrc/u8g_font_fub11.d ./Drivers/fntsrc/u8g_font_fub11.o ./Drivers/fntsrc/u8g_font_fub11.su ./Drivers/fntsrc/u8g_font_fub11n.d ./Drivers/fntsrc/u8g_font_fub11n.o ./Drivers/fntsrc/u8g_font_fub11n.su ./Drivers/fntsrc/u8g_font_fub11r.d ./Drivers/fntsrc/u8g_font_fub11r.o ./Drivers/fntsrc/u8g_font_fub11r.su ./Drivers/fntsrc/u8g_font_fub14.d ./Drivers/fntsrc/u8g_font_fub14.o ./Drivers/fntsrc/u8g_font_fub14.su ./Drivers/fntsrc/u8g_font_fub14n.d ./Drivers/fntsrc/u8g_font_fub14n.o ./Drivers/fntsrc/u8g_font_fub14n.su ./Drivers/fntsrc/u8g_font_fub14r.d ./Drivers/fntsrc/u8g_font_fub14r.o ./Drivers/fntsrc/u8g_font_fub14r.su ./Drivers/fntsrc/u8g_font_fub17.d ./Drivers/fntsrc/u8g_font_fub17.o ./Drivers/fntsrc/u8g_font_fub17.su ./Drivers/fntsrc/u8g_font_fub17n.d ./Drivers/fntsrc/u8g_font_fub17n.o ./Drivers/fntsrc/u8g_font_fub17n.su ./Drivers/fntsrc/u8g_font_fub17r.d ./Drivers/fntsrc/u8g_font_fub17r.o ./Drivers/fntsrc/u8g_font_fub17r.su ./Drivers/fntsrc/u8g_font_fub20.d ./Drivers/fntsrc/u8g_font_fub20.o ./Drivers/fntsrc/u8g_font_fub20.su ./Drivers/fntsrc/u8g_font_fub20n.d ./Drivers/fntsrc/u8g_font_fub20n.o ./Drivers/fntsrc/u8g_font_fub20n.su ./Drivers/fntsrc/u8g_font_fub20r.d ./Drivers/fntsrc/u8g_font_fub20r.o ./Drivers/fntsrc/u8g_font_fub20r.su ./Drivers/fntsrc/u8g_font_fub25.d ./Drivers/fntsrc/u8g_font_fub25.o ./Drivers/fntsrc/u8g_font_fub25.su ./Drivers/fntsrc/u8g_font_fub25n.d ./Drivers/fntsrc/u8g_font_fub25n.o ./Drivers/fntsrc/u8g_font_fub25n.su ./Drivers/fntsrc/u8g_font_fub25r.d ./Drivers/fntsrc/u8g_font_fub25r.o ./Drivers/fntsrc/u8g_font_fub25r.su ./Drivers/fntsrc/u8g_font_fub30.d ./Drivers/fntsrc/u8g_font_fub30.o ./Drivers/fntsrc/u8g_font_fub30.su ./Drivers/fntsrc/u8g_font_fub30n.d ./Drivers/fntsrc/u8g_font_fub30n.o ./Drivers/fntsrc/u8g_font_fub30n.su ./Drivers/fntsrc/u8g_font_fub30r.d ./Drivers/fntsrc/u8g_font_fub30r.o ./Drivers/fntsrc/u8g_font_fub30r.su ./Drivers/fntsrc/u8g_font_fub35n.d ./Drivers/fntsrc/u8g_font_fub35n.o ./Drivers/fntsrc/u8g_font_fub35n.su ./Drivers/fntsrc/u8g_font_fub42n.d ./Drivers/fntsrc/u8g_font_fub42n.o ./Drivers/fntsrc/u8g_font_fub42n.su ./Drivers/fntsrc/u8g_font_fub49n.d ./Drivers/fntsrc/u8g_font_fub49n.o ./Drivers/fntsrc/u8g_font_fub49n.su ./Drivers/fntsrc/u8g_font_fur11.d ./Drivers/fntsrc/u8g_font_fur11.o ./Drivers/fntsrc/u8g_font_fur11.su ./Drivers/fntsrc/u8g_font_fur11n.d ./Drivers/fntsrc/u8g_font_fur11n.o ./Drivers/fntsrc/u8g_font_fur11n.su ./Drivers/fntsrc/u8g_font_fur11r.d ./Drivers/fntsrc/u8g_font_fur11r.o ./Drivers/fntsrc/u8g_font_fur11r.su ./Drivers/fntsrc/u8g_font_fur14.d ./Drivers/fntsrc/u8g_font_fur14.o ./Drivers/fntsrc/u8g_font_fur14.su ./Drivers/fntsrc/u8g_font_fur14n.d ./Drivers/fntsrc/u8g_font_fur14n.o ./Drivers/fntsrc/u8g_font_fur14n.su ./Drivers/fntsrc/u8g_font_fur14r.d ./Drivers/fntsrc/u8g_font_fur14r.o ./Drivers/fntsrc/u8g_font_fur14r.su ./Drivers/fntsrc/u8g_font_fur17.d ./Drivers/fntsrc/u8g_font_fur17.o ./Drivers/fntsrc/u8g_font_fur17.su ./Drivers/fntsrc/u8g_font_fur17n.d ./Drivers/fntsrc/u8g_font_fur17n.o ./Drivers/fntsrc/u8g_font_fur17n.su ./Drivers/fntsrc/u8g_font_fur17r.d ./Drivers/fntsrc/u8g_font_fur17r.o ./Drivers/fntsrc/u8g_font_fur17r.su ./Drivers/fntsrc/u8g_font_fur20.d ./Drivers/fntsrc/u8g_font_fur20.o ./Drivers/fntsrc/u8g_font_fur20.su ./Drivers/fntsrc/u8g_font_fur20n.d ./Drivers/fntsrc/u8g_font_fur20n.o ./Drivers/fntsrc/u8g_font_fur20n.su ./Drivers/fntsrc/u8g_font_fur20r.d ./Drivers/fntsrc/u8g_font_fur20r.o ./Drivers/fntsrc/u8g_font_fur20r.su ./Drivers/fntsrc/u8g_font_fur25.d ./Drivers/fntsrc/u8g_font_fur25.o ./Drivers/fntsrc/u8g_font_fur25.su ./Drivers/fntsrc/u8g_font_fur25n.d ./Drivers/fntsrc/u8g_font_fur25n.o ./Drivers/fntsrc/u8g_font_fur25n.su ./Drivers/fntsrc/u8g_font_fur25r.d ./Drivers/fntsrc/u8g_font_fur25r.o ./Drivers/fntsrc/u8g_font_fur25r.su ./Drivers/fntsrc/u8g_font_fur30.d ./Drivers/fntsrc/u8g_font_fur30.o ./Drivers/fntsrc/u8g_font_fur30.su ./Drivers/fntsrc/u8g_font_fur30n.d ./Drivers/fntsrc/u8g_font_fur30n.o ./Drivers/fntsrc/u8g_font_fur30n.su ./Drivers/fntsrc/u8g_font_fur30r.d ./Drivers/fntsrc/u8g_font_fur30r.o ./Drivers/fntsrc/u8g_font_fur30r.su ./Drivers/fntsrc/u8g_font_fur35n.d ./Drivers/fntsrc/u8g_font_fur35n.o ./Drivers/fntsrc/u8g_font_fur35n.su ./Drivers/fntsrc/u8g_font_fur42n.d ./Drivers/fntsrc/u8g_font_fur42n.o ./Drivers/fntsrc/u8g_font_fur42n.su ./Drivers/fntsrc/u8g_font_fur49n.d ./Drivers/fntsrc/u8g_font_fur49n.o ./Drivers/fntsrc/u8g_font_fur49n.su ./Drivers/fntsrc/u8g_font_gdb11.d ./Drivers/fntsrc/u8g_font_gdb11.o ./Drivers/fntsrc/u8g_font_gdb11.su ./Drivers/fntsrc/u8g_font_gdb11n.d ./Drivers/fntsrc/u8g_font_gdb11n.o ./Drivers/fntsrc/u8g_font_gdb11n.su ./Drivers/fntsrc/u8g_font_gdb11r.d ./Drivers/fntsrc/u8g_font_gdb11r.o ./Drivers/fntsrc/u8g_font_gdb11r.su ./Drivers/fntsrc/u8g_font_gdb12.d ./Drivers/fntsrc/u8g_font_gdb12.o ./Drivers/fntsrc/u8g_font_gdb12.su ./Drivers/fntsrc/u8g_font_gdb12n.d ./Drivers/fntsrc/u8g_font_gdb12n.o ./Drivers/fntsrc/u8g_font_gdb12n.su ./Drivers/fntsrc/u8g_font_gdb12r.d ./Drivers/fntsrc/u8g_font_gdb12r.o ./Drivers/fntsrc/u8g_font_gdb12r.su ./Drivers/fntsrc/u8g_font_gdb14.d ./Drivers/fntsrc/u8g_font_gdb14.o ./Drivers/fntsrc/u8g_font_gdb14.su ./Drivers/fntsrc/u8g_font_gdb14n.d ./Drivers/fntsrc/u8g_font_gdb14n.o ./Drivers/fntsrc/u8g_font_gdb14n.su ./Drivers/fntsrc/u8g_font_gdb14r.d ./Drivers/fntsrc/u8g_font_gdb14r.o ./Drivers/fntsrc/u8g_font_gdb14r.su ./Drivers/fntsrc/u8g_font_gdb17.d ./Drivers/fntsrc/u8g_font_gdb17.o
	-$(RM) ./Drivers/fntsrc/u8g_font_gdb17.su ./Drivers/fntsrc/u8g_font_gdb17n.d ./Drivers/fntsrc/u8g_font_gdb17n.o ./Drivers/fntsrc/u8g_font_gdb17n.su ./Drivers/fntsrc/u8g_font_gdb17r.d ./Drivers/fntsrc/u8g_font_gdb17r.o ./Drivers/fntsrc/u8g_font_gdb17r.su ./Drivers/fntsrc/u8g_font_gdb20.d ./Drivers/fntsrc/u8g_font_gdb20.o ./Drivers/fntsrc/u8g_font_gdb20.su ./Drivers/fntsrc/u8g_font_gdb20n.d ./Drivers/fntsrc/u8g_font_gdb20n.o ./Drivers/fntsrc/u8g_font_gdb20n.su ./Drivers/fntsrc/u8g_font_gdb20r.d ./Drivers/fntsrc/u8g_font_gdb20r.o ./Drivers/fntsrc/u8g_font_gdb20r.su ./Drivers/fntsrc/u8g_font_gdb25.d ./Drivers/fntsrc/u8g_font_gdb25.o ./Drivers/fntsrc/u8g_font_gdb25.su ./Drivers/fntsrc/u8g_font_gdb25n.d ./Drivers/fntsrc/u8g_font_gdb25n.o ./Drivers/fntsrc/u8g_font_gdb25n.su ./Drivers/fntsrc/u8g_font_gdb25r.d ./Drivers/fntsrc/u8g_font_gdb25r.o ./Drivers/fntsrc/u8g_font_gdb25r.su ./Drivers/fntsrc/u8g_font_gdb30.d ./Drivers/fntsrc/u8g_font_gdb30.o ./Drivers/fntsrc/u8g_font_gdb30.su ./Drivers/fntsrc/u8g_font_gdb30n.d ./Drivers/fntsrc/u8g_font_gdb30n.o ./Drivers/fntsrc/u8g_font_gdb30n.su ./Drivers/fntsrc/u8g_font_gdb30r.d ./Drivers/fntsrc/u8g_font_gdb30r.o ./Drivers/fntsrc/u8g_font_gdb30r.su ./Drivers/fntsrc/u8g_font_gdr10.d ./Drivers/fntsrc/u8g_font_gdr10.o ./Drivers/fntsrc/u8g_font_gdr10.su ./Drivers/fntsrc/u8g_font_gdr10n.d ./Drivers/fntsrc/u8g_font_gdr10n.o ./Drivers/fntsrc/u8g_font_gdr10n.su ./Drivers/fntsrc/u8g_font_gdr10r.d ./Drivers/fntsrc/u8g_font_gdr10r.o ./Drivers/fntsrc/u8g_font_gdr10r.su ./Drivers/fntsrc/u8g_font_gdr11.d ./Drivers/fntsrc/u8g_font_gdr11.o ./Drivers/fntsrc/u8g_font_gdr11.su ./Drivers/fntsrc/u8g_font_gdr11n.d ./Drivers/fntsrc/u8g_font_gdr11n.o ./Drivers/fntsrc/u8g_font_gdr11n.su ./Drivers/fntsrc/u8g_font_gdr11r.d ./Drivers/fntsrc/u8g_font_gdr11r.o ./Drivers/fntsrc/u8g_font_gdr11r.su ./Drivers/fntsrc/u8g_font_gdr12.d ./Drivers/fntsrc/u8g_font_gdr12.o ./Drivers/fntsrc/u8g_font_gdr12.su ./Drivers/fntsrc/u8g_font_gdr12n.d ./Drivers/fntsrc/u8g_font_gdr12n.o ./Drivers/fntsrc/u8g_font_gdr12n.su ./Drivers/fntsrc/u8g_font_gdr12r.d ./Drivers/fntsrc/u8g_font_gdr12r.o ./Drivers/fntsrc/u8g_font_gdr12r.su ./Drivers/fntsrc/u8g_font_gdr14.d ./Drivers/fntsrc/u8g_font_gdr14.o ./Drivers/fntsrc/u8g_font_gdr14.su ./Drivers/fntsrc/u8g_font_gdr14n.d ./Drivers/fntsrc/u8g_font_gdr14n.o ./Drivers/fntsrc/u8g_font_gdr14n.su ./Drivers/fntsrc/u8g_font_gdr14r.d ./Drivers/fntsrc/u8g_font_gdr14r.o ./Drivers/fntsrc/u8g_font_gdr14r.su ./Drivers/fntsrc/u8g_font_gdr17.d ./Drivers/fntsrc/u8g_font_gdr17.o ./Drivers/fntsrc/u8g_font_gdr17.su ./Drivers/fntsrc/u8g_font_gdr17n.d ./Drivers/fntsrc/u8g_font_gdr17n.o ./Drivers/fntsrc/u8g_font_gdr17n.su ./Drivers/fntsrc/u8g_font_gdr17r.d ./Drivers/fntsrc/u8g_font_gdr17r.o ./Drivers/fntsrc/u8g_font_gdr17r.su ./Drivers/fntsrc/u8g_font_gdr20.d ./Drivers/fntsrc/u8g_font_gdr20.o ./Drivers/fntsrc/u8g_font_gdr20.su ./Drivers/fntsrc/u8g_font_gdr20n.d ./Drivers/fntsrc/u8g_font_gdr20n.o ./Drivers/fntsrc/u8g_font_gdr20n.su ./Drivers/fntsrc/u8g_font_gdr20r.d ./Drivers/fntsrc/u8g_font_gdr20r.o ./Drivers/fntsrc/u8g_font_gdr20r.su ./Drivers/fntsrc/u8g_font_gdr25.d ./Drivers/fntsrc/u8g_font_gdr25.o ./Drivers/fntsrc/u8g_font_gdr25.su ./Drivers/fntsrc/u8g_font_gdr25n.d ./Drivers/fntsrc/u8g_font_gdr25n.o ./Drivers/fntsrc/u8g_font_gdr25n.su ./Drivers/fntsrc/u8g_font_gdr25r.d ./Drivers/fntsrc/u8g_font_gdr25r.o ./Drivers/fntsrc/u8g_font_gdr25r.su ./Drivers/fntsrc/u8g_font_gdr30.d ./Drivers/fntsrc/u8g_font_gdr30.o ./Drivers/fntsrc/u8g_font_gdr30.su ./Drivers/fntsrc/u8g_font_gdr30n.d ./Drivers/fntsrc/u8g_font_gdr30n.o ./Drivers/fntsrc/u8g_font_gdr30n.su ./Drivers/fntsrc/u8g_font_gdr30r.d ./Drivers/fntsrc/u8g_font_gdr30r.o ./Drivers/fntsrc/u8g_font_gdr30r.su ./Drivers/fntsrc/u8g_font_gdr9.d ./Drivers/fntsrc/u8g_font_gdr9.o ./Drivers/fntsrc/u8g_font_gdr9.su ./Drivers/fntsrc/u8g_font_gdr9n.d ./Drivers/fntsrc/u8g_font_gdr9n.o ./Drivers/fntsrc/u8g_font_gdr9n.su ./Drivers/fntsrc/u8g_font_gdr9r.d ./Drivers/fntsrc/u8g_font_gdr9r.o ./Drivers/fntsrc/u8g_font_gdr9r.su ./Drivers/fntsrc/u8g_font_helvb08.d ./Drivers/fntsrc/u8g_font_helvb08.o ./Drivers/fntsrc/u8g_font_helvb08.su ./Drivers/fntsrc/u8g_font_helvb08n.d ./Drivers/fntsrc/u8g_font_helvb08n.o ./Drivers/fntsrc/u8g_font_helvb08n.su ./Drivers/fntsrc/u8g_font_helvb08r.d ./Drivers/fntsrc/u8g_font_helvb08r.o ./Drivers/fntsrc/u8g_font_helvb08r.su ./Drivers/fntsrc/u8g_font_helvb10.d ./Drivers/fntsrc/u8g_font_helvb10.o ./Drivers/fntsrc/u8g_font_helvb10.su ./Drivers/fntsrc/u8g_font_helvb10n.d ./Drivers/fntsrc/u8g_font_helvb10n.o ./Drivers/fntsrc/u8g_font_helvb10n.su ./Drivers/fntsrc/u8g_font_helvb10r.d ./Drivers/fntsrc/u8g_font_helvb10r.o ./Drivers/fntsrc/u8g_font_helvb10r.su ./Drivers/fntsrc/u8g_font_helvb12.d ./Drivers/fntsrc/u8g_font_helvb12.o ./Drivers/fntsrc/u8g_font_helvb12.su ./Drivers/fntsrc/u8g_font_helvb12n.d ./Drivers/fntsrc/u8g_font_helvb12n.o ./Drivers/fntsrc/u8g_font_helvb12n.su ./Drivers/fntsrc/u8g_font_helvb12r.d ./Drivers/fntsrc/u8g_font_helvb12r.o ./Drivers/fntsrc/u8g_font_helvb12r.su ./Drivers/fntsrc/u8g_font_helvb14.d ./Drivers/fntsrc/u8g_font_helvb14.o ./Drivers/fntsrc/u8g_font_helvb14.su ./Drivers/fntsrc/u8g_font_helvb14n.d ./Drivers/fntsrc/u8g_font_helvb14n.o ./Drivers/fntsrc/u8g_font_helvb14n.su ./Drivers/fntsrc/u8g_font_helvb14r.d ./Drivers/fntsrc/u8g_font_helvb14r.o ./Drivers/fntsrc/u8g_font_helvb14r.su ./Drivers/fntsrc/u8g_font_helvb18.d ./Drivers/fntsrc/u8g_font_helvb18.o ./Drivers/fntsrc/u8g_font_helvb18.su ./Drivers/fntsrc/u8g_font_helvb18n.d ./Drivers/fntsrc/u8g_font_helvb18n.o ./Drivers/fntsrc/u8g_font_helvb18n.su ./Drivers/fntsrc/u8g_font_helvb18r.d ./Drivers/fntsrc/u8g_font_helvb18r.o ./Drivers/fntsrc/u8g_font_helvb18r.su ./Drivers/fntsrc/u8g_font_helvb24.d ./Drivers/fntsrc/u8g_font_helvb24.o ./Drivers/fntsrc/u8g_font_helvb24.su ./Drivers/fntsrc/u8g_font_helvb24n.d ./Drivers/fntsrc/u8g_font_helvb24n.o ./Drivers/fntsrc/u8g_font_helvb24n.su ./Drivers/fntsrc/u8g_font_helvb24r.d ./Drivers/fntsrc/u8g_font_helvb24r.o
	-$(RM) ./Drivers/fntsrc/u8g_font_helvb24r.su ./Drivers/fntsrc/u8g_font_helvr08.d ./Drivers/fntsrc/u8g_font_helvr08.o ./Drivers/fntsrc/u8g_font_helvr08.su ./Drivers/fntsrc/u8g_font_helvr08r.d ./Drivers/fntsrc/u8g_font_helvr08r.o ./Drivers/fntsrc/u8g_font_helvr08r.su ./Drivers/fntsrc/u8g_font_helvr10.d ./Drivers/fntsrc/u8g_font_helvr10.o ./Drivers/fntsrc/u8g_font_helvr10.su ./Drivers/fntsrc/u8g_font_helvr10r.d ./Drivers/fntsrc/u8g_font_helvr10r.o ./Drivers/fntsrc/u8g_font_helvr10r.su ./Drivers/fntsrc/u8g_font_helvr12.d ./Drivers/fntsrc/u8g_font_helvr12.o ./Drivers/fntsrc/u8g_font_helvr12.su ./Drivers/fntsrc/u8g_font_helvr12r.d ./Drivers/fntsrc/u8g_font_helvr12r.o ./Drivers/fntsrc/u8g_font_helvr12r.su ./Drivers/fntsrc/u8g_font_helvr14.d ./Drivers/fntsrc/u8g_font_helvr14.o ./Drivers/fntsrc/u8g_font_helvr14.su ./Drivers/fntsrc/u8g_font_helvr14r.d ./Drivers/fntsrc/u8g_font_helvr14r.o ./Drivers/fntsrc/u8g_font_helvr14r.su ./Drivers/fntsrc/u8g_font_helvr18.d ./Drivers/fntsrc/u8g_font_helvr18.o ./Drivers/fntsrc/u8g_font_helvr18.su ./Drivers/fntsrc/u8g_font_helvr18r.d ./Drivers/fntsrc/u8g_font_helvr18r.o ./Drivers/fntsrc/u8g_font_helvr18r.su ./Drivers/fntsrc/u8g_font_helvr24.d ./Drivers/fntsrc/u8g_font_helvr24.o ./Drivers/fntsrc/u8g_font_helvr24.su ./Drivers/fntsrc/u8g_font_helvr24n.d ./Drivers/fntsrc/u8g_font_helvr24n.o ./Drivers/fntsrc/u8g_font_helvr24n.su ./Drivers/fntsrc/u8g_font_helvr24r.d ./Drivers/fntsrc/u8g_font_helvr24r.o ./Drivers/fntsrc/u8g_font_helvr24r.su ./Drivers/fntsrc/u8g_font_lucasfont_alternate.d ./Drivers/fntsrc/u8g_font_lucasfont_alternate.o ./Drivers/fntsrc/u8g_font_lucasfont_alternate.su ./Drivers/fntsrc/u8g_font_lucasfont_alternaten.d ./Drivers/fntsrc/u8g_font_lucasfont_alternaten.o ./Drivers/fntsrc/u8g_font_lucasfont_alternaten.su ./Drivers/fntsrc/u8g_font_lucasfont_alternater.d ./Drivers/fntsrc/u8g_font_lucasfont_alternater.o ./Drivers/fntsrc/u8g_font_lucasfont_alternater.su ./Drivers/fntsrc/u8g_font_m2icon_5.d ./Drivers/fntsrc/u8g_font_m2icon_5.o ./Drivers/fntsrc/u8g_font_m2icon_5.su ./Drivers/fntsrc/u8g_font_m2icon_7.d ./Drivers/fntsrc/u8g_font_m2icon_7.o ./Drivers/fntsrc/u8g_font_m2icon_7.su ./Drivers/fntsrc/u8g_font_m2icon_9.d ./Drivers/fntsrc/u8g_font_m2icon_9.o ./Drivers/fntsrc/u8g_font_m2icon_9.su ./Drivers/fntsrc/u8g_font_micro.d ./Drivers/fntsrc/u8g_font_micro.o ./Drivers/fntsrc/u8g_font_micro.su ./Drivers/fntsrc/u8g_font_ncenb08.d ./Drivers/fntsrc/u8g_font_ncenb08.o ./Drivers/fntsrc/u8g_font_ncenb08.su ./Drivers/fntsrc/u8g_font_ncenb08r.d ./Drivers/fntsrc/u8g_font_ncenb08r.o ./Drivers/fntsrc/u8g_font_ncenb08r.su ./Drivers/fntsrc/u8g_font_ncenb10.d ./Drivers/fntsrc/u8g_font_ncenb10.o ./Drivers/fntsrc/u8g_font_ncenb10.su ./Drivers/fntsrc/u8g_font_ncenb10r.d ./Drivers/fntsrc/u8g_font_ncenb10r.o ./Drivers/fntsrc/u8g_font_ncenb10r.su ./Drivers/fntsrc/u8g_font_ncenb12.d ./Drivers/fntsrc/u8g_font_ncenb12.o ./Drivers/fntsrc/u8g_font_ncenb12.su ./Drivers/fntsrc/u8g_font_ncenb12r.d ./Drivers/fntsrc/u8g_font_ncenb12r.o ./Drivers/fntsrc/u8g_font_ncenb12r.su ./Drivers/fntsrc/u8g_font_ncenb14.d ./Drivers/fntsrc/u8g_font_ncenb14.o ./Drivers/fntsrc/u8g_font_ncenb14.su ./Drivers/fntsrc/u8g_font_ncenb14r.d ./Drivers/fntsrc/u8g_font_ncenb14r.o ./Drivers/fntsrc/u8g_font_ncenb14r.su ./Drivers/fntsrc/u8g_font_ncenb18.d ./Drivers/fntsrc/u8g_font_ncenb18.o ./Drivers/fntsrc/u8g_font_ncenb18.su ./Drivers/fntsrc/u8g_font_ncenb18r.d ./Drivers/fntsrc/u8g_font_ncenb18r.o ./Drivers/fntsrc/u8g_font_ncenb18r.su ./Drivers/fntsrc/u8g_font_ncenb24.d ./Drivers/fntsrc/u8g_font_ncenb24.o ./Drivers/fntsrc/u8g_font_ncenb24.su ./Drivers/fntsrc/u8g_font_ncenb24n.d ./Drivers/fntsrc/u8g_font_ncenb24n.o ./Drivers/fntsrc/u8g_font_ncenb24n.su ./Drivers/fntsrc/u8g_font_ncenb24r.d ./Drivers/fntsrc/u8g_font_ncenb24r.o ./Drivers/fntsrc/u8g_font_ncenb24r.su ./Drivers/fntsrc/u8g_font_ncenr08.d ./Drivers/fntsrc/u8g_font_ncenr08.o ./Drivers/fntsrc/u8g_font_ncenr08.su ./Drivers/fntsrc/u8g_font_ncenr08r.d ./Drivers/fntsrc/u8g_font_ncenr08r.o ./Drivers/fntsrc/u8g_font_ncenr08r.su ./Drivers/fntsrc/u8g_font_ncenr10.d ./Drivers/fntsrc/u8g_font_ncenr10.o ./Drivers/fntsrc/u8g_font_ncenr10.su ./Drivers/fntsrc/u8g_font_ncenr10r.d ./Drivers/fntsrc/u8g_font_ncenr10r.o ./Drivers/fntsrc/u8g_font_ncenr10r.su ./Drivers/fntsrc/u8g_font_ncenr12.d ./Drivers/fntsrc/u8g_font_ncenr12.o ./Drivers/fntsrc/u8g_font_ncenr12.su ./Drivers/fntsrc/u8g_font_ncenr12r.d ./Drivers/fntsrc/u8g_font_ncenr12r.o ./Drivers/fntsrc/u8g_font_ncenr12r.su ./Drivers/fntsrc/u8g_font_ncenr14.d ./Drivers/fntsrc/u8g_font_ncenr14.o ./Drivers/fntsrc/u8g_font_ncenr14.su ./Drivers/fntsrc/u8g_font_ncenr14r.d ./Drivers/fntsrc/u8g_font_ncenr14r.o ./Drivers/fntsrc/u8g_font_ncenr14r.su ./Drivers/fntsrc/u8g_font_ncenr18.d ./Drivers/fntsrc/u8g_font_ncenr18.o ./Drivers/fntsrc/u8g_font_ncenr18.su ./Drivers/fntsrc/u8g_font_ncenr18r.d ./Drivers/fntsrc/u8g_font_ncenr18r.o ./Drivers/fntsrc/u8g_font_ncenr18r.su ./Drivers/fntsrc/u8g_font_ncenr24.d ./Drivers/fntsrc/u8g_font_ncenr24.o ./Drivers/fntsrc/u8g_font_ncenr24.su ./Drivers/fntsrc/u8g_font_ncenr24n.d ./Drivers/fntsrc/u8g_font_ncenr24n.o ./Drivers/fntsrc/u8g_font_ncenr24n.su ./Drivers/fntsrc/u8g_font_ncenr24r.d ./Drivers/fntsrc/u8g_font_ncenr24r.o ./Drivers/fntsrc/u8g_font_ncenr24r.su ./Drivers/fntsrc/u8g_font_orgv01.d ./Drivers/fntsrc/u8g_font_orgv01.o ./Drivers/fntsrc/u8g_font_orgv01.su ./Drivers/fntsrc/u8g_font_orgv01n.d ./Drivers/fntsrc/u8g_font_orgv01n.o ./Drivers/fntsrc/u8g_font_orgv01n.su ./Drivers/fntsrc/u8g_font_orgv01r.d ./Drivers/fntsrc/u8g_font_orgv01r.o ./Drivers/fntsrc/u8g_font_orgv01r.su ./Drivers/fntsrc/u8g_font_osb18.d ./Drivers/fntsrc/u8g_font_osb18.o ./Drivers/fntsrc/u8g_font_osb18.su ./Drivers/fntsrc/u8g_font_osb18n.d ./Drivers/fntsrc/u8g_font_osb18n.o ./Drivers/fntsrc/u8g_font_osb18n.su ./Drivers/fntsrc/u8g_font_osb18r.d ./Drivers/fntsrc/u8g_font_osb18r.o ./Drivers/fntsrc/u8g_font_osb18r.su ./Drivers/fntsrc/u8g_font_osb21.d ./Drivers/fntsrc/u8g_font_osb21.o ./Drivers/fntsrc/u8g_font_osb21.su
	-$(RM) ./Drivers/fntsrc/u8g_font_osb21n.d ./Drivers/fntsrc/u8g_font_osb21n.o ./Drivers/fntsrc/u8g_font_osb21n.su ./Drivers/fntsrc/u8g_font_osb21r.d ./Drivers/fntsrc/u8g_font_osb21r.o ./Drivers/fntsrc/u8g_font_osb21r.su ./Drivers/fntsrc/u8g_font_osb26.d ./Drivers/fntsrc/u8g_font_osb26.o ./Drivers/fntsrc/u8g_font_osb26.su ./Drivers/fntsrc/u8g_font_osb26n.d ./Drivers/fntsrc/u8g_font_osb26n.o ./Drivers/fntsrc/u8g_font_osb26n.su ./Drivers/fntsrc/u8g_font_osb26r.d ./Drivers/fntsrc/u8g_font_osb26r.o ./Drivers/fntsrc/u8g_font_osb26r.su ./Drivers/fntsrc/u8g_font_osb29.d ./Drivers/fntsrc/u8g_font_osb29.o ./Drivers/fntsrc/u8g_font_osb29.su ./Drivers/fntsrc/u8g_font_osb29n.d ./Drivers/fntsrc/u8g_font_osb29n.o ./Drivers/fntsrc/u8g_font_osb29n.su ./Drivers/fntsrc/u8g_font_osb29r.d ./Drivers/fntsrc/u8g_font_osb29r.o ./Drivers/fntsrc/u8g_font_osb29r.su ./Drivers/fntsrc/u8g_font_osb35.d ./Drivers/fntsrc/u8g_font_osb35.o ./Drivers/fntsrc/u8g_font_osb35.su ./Drivers/fntsrc/u8g_font_osb35n.d ./Drivers/fntsrc/u8g_font_osb35n.o ./Drivers/fntsrc/u8g_font_osb35n.su ./Drivers/fntsrc/u8g_font_osb35r.d ./Drivers/fntsrc/u8g_font_osb35r.o ./Drivers/fntsrc/u8g_font_osb35r.su ./Drivers/fntsrc/u8g_font_osr18.d ./Drivers/fntsrc/u8g_font_osr18.o ./Drivers/fntsrc/u8g_font_osr18.su ./Drivers/fntsrc/u8g_font_osr18n.d ./Drivers/fntsrc/u8g_font_osr18n.o ./Drivers/fntsrc/u8g_font_osr18n.su ./Drivers/fntsrc/u8g_font_osr18r.d ./Drivers/fntsrc/u8g_font_osr18r.o ./Drivers/fntsrc/u8g_font_osr18r.su ./Drivers/fntsrc/u8g_font_osr21.d ./Drivers/fntsrc/u8g_font_osr21.o ./Drivers/fntsrc/u8g_font_osr21.su ./Drivers/fntsrc/u8g_font_osr21n.d ./Drivers/fntsrc/u8g_font_osr21n.o ./Drivers/fntsrc/u8g_font_osr21n.su ./Drivers/fntsrc/u8g_font_osr21r.d ./Drivers/fntsrc/u8g_font_osr21r.o ./Drivers/fntsrc/u8g_font_osr21r.su ./Drivers/fntsrc/u8g_font_osr26.d ./Drivers/fntsrc/u8g_font_osr26.o ./Drivers/fntsrc/u8g_font_osr26.su ./Drivers/fntsrc/u8g_font_osr26n.d ./Drivers/fntsrc/u8g_font_osr26n.o ./Drivers/fntsrc/u8g_font_osr26n.su ./Drivers/fntsrc/u8g_font_osr26r.d ./Drivers/fntsrc/u8g_font_osr26r.o ./Drivers/fntsrc/u8g_font_osr26r.su ./Drivers/fntsrc/u8g_font_osr29.d ./Drivers/fntsrc/u8g_font_osr29.o ./Drivers/fntsrc/u8g_font_osr29.su ./Drivers/fntsrc/u8g_font_osr29n.d ./Drivers/fntsrc/u8g_font_osr29n.o ./Drivers/fntsrc/u8g_font_osr29n.su ./Drivers/fntsrc/u8g_font_osr29r.d ./Drivers/fntsrc/u8g_font_osr29r.o ./Drivers/fntsrc/u8g_font_osr29r.su ./Drivers/fntsrc/u8g_font_osr35.d ./Drivers/fntsrc/u8g_font_osr35.o ./Drivers/fntsrc/u8g_font_osr35.su ./Drivers/fntsrc/u8g_font_osr35n.d ./Drivers/fntsrc/u8g_font_osr35n.o ./Drivers/fntsrc/u8g_font_osr35n.su ./Drivers/fntsrc/u8g_font_osr35r.d ./Drivers/fntsrc/u8g_font_osr35r.o ./Drivers/fntsrc/u8g_font_osr35r.su ./Drivers/fntsrc/u8g_font_p01type.d ./Drivers/fntsrc/u8g_font_p01type.o ./Drivers/fntsrc/u8g_font_p01type.su ./Drivers/fntsrc/u8g_font_p01typen.d ./Drivers/fntsrc/u8g_font_p01typen.o ./Drivers/fntsrc/u8g_font_p01typen.su ./Drivers/fntsrc/u8g_font_p01typer.d ./Drivers/fntsrc/u8g_font_p01typer.o ./Drivers/fntsrc/u8g_font_p01typer.su ./Drivers/fntsrc/u8g_font_pixelle_micro.d ./Drivers/fntsrc/u8g_font_pixelle_micro.o ./Drivers/fntsrc/u8g_font_pixelle_micro.su ./Drivers/fntsrc/u8g_font_pixelle_micron.d ./Drivers/fntsrc/u8g_font_pixelle_micron.o ./Drivers/fntsrc/u8g_font_pixelle_micron.su ./Drivers/fntsrc/u8g_font_pixelle_micror.d ./Drivers/fntsrc/u8g_font_pixelle_micror.o ./Drivers/fntsrc/u8g_font_pixelle_micror.su ./Drivers/fntsrc/u8g_font_profont10.d ./Drivers/fntsrc/u8g_font_profont10.o ./Drivers/fntsrc/u8g_font_profont10.su ./Drivers/fntsrc/u8g_font_profont10r.d ./Drivers/fntsrc/u8g_font_profont10r.o ./Drivers/fntsrc/u8g_font_profont10r.su ./Drivers/fntsrc/u8g_font_profont11.d ./Drivers/fntsrc/u8g_font_profont11.o ./Drivers/fntsrc/u8g_font_profont11.su ./Drivers/fntsrc/u8g_font_profont11r.d ./Drivers/fntsrc/u8g_font_profont11r.o ./Drivers/fntsrc/u8g_font_profont11r.su ./Drivers/fntsrc/u8g_font_profont12.d ./Drivers/fntsrc/u8g_font_profont12.o ./Drivers/fntsrc/u8g_font_profont12.su ./Drivers/fntsrc/u8g_font_profont12r.d ./Drivers/fntsrc/u8g_font_profont12r.o ./Drivers/fntsrc/u8g_font_profont12r.su ./Drivers/fntsrc/u8g_font_profont15.d ./Drivers/fntsrc/u8g_font_profont15.o ./Drivers/fntsrc/u8g_font_profont15.su ./Drivers/fntsrc/u8g_font_profont15r.d ./Drivers/fntsrc/u8g_font_profont15r.o ./Drivers/fntsrc/u8g_font_profont15r.su ./Drivers/fntsrc/u8g_font_profont17.d ./Drivers/fntsrc/u8g_font_profont17.o ./Drivers/fntsrc/u8g_font_profont17.su ./Drivers/fntsrc/u8g_font_profont17r.d ./Drivers/fntsrc/u8g_font_profont17r.o ./Drivers/fntsrc/u8g_font_profont17r.su ./Drivers/fntsrc/u8g_font_profont22.d ./Drivers/fntsrc/u8g_font_profont22.o ./Drivers/fntsrc/u8g_font_profont22.su ./Drivers/fntsrc/u8g_font_profont22r.d ./Drivers/fntsrc/u8g_font_profont22r.o ./Drivers/fntsrc/u8g_font_profont22r.su ./Drivers/fntsrc/u8g_font_profont29.d ./Drivers/fntsrc/u8g_font_profont29.o ./Drivers/fntsrc/u8g_font_profont29.su ./Drivers/fntsrc/u8g_font_profont29r.d ./Drivers/fntsrc/u8g_font_profont29r.o ./Drivers/fntsrc/u8g_font_profont29r.su ./Drivers/fntsrc/u8g_font_robot_de_niro.d ./Drivers/fntsrc/u8g_font_robot_de_niro.o ./Drivers/fntsrc/u8g_font_robot_de_niro.su ./Drivers/fntsrc/u8g_font_robot_de_niron.d ./Drivers/fntsrc/u8g_font_robot_de_niron.o ./Drivers/fntsrc/u8g_font_robot_de_niron.su ./Drivers/fntsrc/u8g_font_robot_de_niror.d ./Drivers/fntsrc/u8g_font_robot_de_niror.o ./Drivers/fntsrc/u8g_font_robot_de_niror.su ./Drivers/fntsrc/u8g_font_symb08.d ./Drivers/fntsrc/u8g_font_symb08.o ./Drivers/fntsrc/u8g_font_symb08.su ./Drivers/fntsrc/u8g_font_symb08r.d ./Drivers/fntsrc/u8g_font_symb08r.o ./Drivers/fntsrc/u8g_font_symb08r.su ./Drivers/fntsrc/u8g_font_symb10.d ./Drivers/fntsrc/u8g_font_symb10.o ./Drivers/fntsrc/u8g_font_symb10.su ./Drivers/fntsrc/u8g_font_symb10r.d ./Drivers/fntsrc/u8g_font_symb10r.o ./Drivers/fntsrc/u8g_font_symb10r.su ./Drivers/fntsrc/u8g_font_symb12.d ./Drivers/fntsrc/u8g_font_symb12.o
	-$(RM) ./Drivers/fntsrc/u8g_font_symb12.su ./Drivers/fntsrc/u8g_font_symb12r.d ./Drivers/fntsrc/u8g_font_symb12r.o ./Drivers/fntsrc/u8g_font_symb12r.su ./Drivers/fntsrc/u8g_font_symb14.d ./Drivers/fntsrc/u8g_font_symb14.o ./Drivers/fntsrc/u8g_font_symb14.su ./Drivers/fntsrc/u8g_font_symb14r.d ./Drivers/fntsrc/u8g_font_symb14r.o ./Drivers/fntsrc/u8g_font_symb14r.su ./Drivers/fntsrc/u8g_font_symb18.d ./Drivers/fntsrc/u8g_font_symb18.o ./Drivers/fntsrc/u8g_font_symb18.su ./Drivers/fntsrc/u8g_font_symb18r.d ./Drivers/fntsrc/u8g_font_symb18r.o ./Drivers/fntsrc/u8g_font_symb18r.su ./Drivers/fntsrc/u8g_font_symb24.d ./Drivers/fntsrc/u8g_font_symb24.o ./Drivers/fntsrc/u8g_font_symb24.su ./Drivers/fntsrc/u8g_font_symb24r.d ./Drivers/fntsrc/u8g_font_symb24r.o ./Drivers/fntsrc/u8g_font_symb24r.su ./Drivers/fntsrc/u8g_font_timb08.d ./Drivers/fntsrc/u8g_font_timb08.o ./Drivers/fntsrc/u8g_font_timb08.su ./Drivers/fntsrc/u8g_font_timb08r.d ./Drivers/fntsrc/u8g_font_timb08r.o ./Drivers/fntsrc/u8g_font_timb08r.su ./Drivers/fntsrc/u8g_font_timb10.d ./Drivers/fntsrc/u8g_font_timb10.o ./Drivers/fntsrc/u8g_font_timb10.su ./Drivers/fntsrc/u8g_font_timb10r.d ./Drivers/fntsrc/u8g_font_timb10r.o ./Drivers/fntsrc/u8g_font_timb10r.su ./Drivers/fntsrc/u8g_font_timb12.d ./Drivers/fntsrc/u8g_font_timb12.o ./Drivers/fntsrc/u8g_font_timb12.su ./Drivers/fntsrc/u8g_font_timb12r.d ./Drivers/fntsrc/u8g_font_timb12r.o ./Drivers/fntsrc/u8g_font_timb12r.su ./Drivers/fntsrc/u8g_font_timb14.d ./Drivers/fntsrc/u8g_font_timb14.o ./Drivers/fntsrc/u8g_font_timb14.su ./Drivers/fntsrc/u8g_font_timb14r.d ./Drivers/fntsrc/u8g_font_timb14r.o ./Drivers/fntsrc/u8g_font_timb14r.su ./Drivers/fntsrc/u8g_font_timb18.d ./Drivers/fntsrc/u8g_font_timb18.o ./Drivers/fntsrc/u8g_font_timb18.su ./Drivers/fntsrc/u8g_font_timb18r.d ./Drivers/fntsrc/u8g_font_timb18r.o ./Drivers/fntsrc/u8g_font_timb18r.su ./Drivers/fntsrc/u8g_font_timb24.d ./Drivers/fntsrc/u8g_font_timb24.o ./Drivers/fntsrc/u8g_font_timb24.su ./Drivers/fntsrc/u8g_font_timb24n.d ./Drivers/fntsrc/u8g_font_timb24n.o ./Drivers/fntsrc/u8g_font_timb24n.su ./Drivers/fntsrc/u8g_font_timb24r.d ./Drivers/fntsrc/u8g_font_timb24r.o ./Drivers/fntsrc/u8g_font_timb24r.su ./Drivers/fntsrc/u8g_font_timr08.d ./Drivers/fntsrc/u8g_font_timr08.o ./Drivers/fntsrc/u8g_font_timr08.su ./Drivers/fntsrc/u8g_font_timr08r.d ./Drivers/fntsrc/u8g_font_timr08r.o ./Drivers/fntsrc/u8g_font_timr08r.su ./Drivers/fntsrc/u8g_font_timr10.d ./Drivers/fntsrc/u8g_font_timr10.o ./Drivers/fntsrc/u8g_font_timr10.su ./Drivers/fntsrc/u8g_font_timr10r.d ./Drivers/fntsrc/u8g_font_timr10r.o ./Drivers/fntsrc/u8g_font_timr10r.su ./Drivers/fntsrc/u8g_font_timr12.d ./Drivers/fntsrc/u8g_font_timr12.o ./Drivers/fntsrc/u8g_font_timr12.su ./Drivers/fntsrc/u8g_font_timr12r.d ./Drivers/fntsrc/u8g_font_timr12r.o ./Drivers/fntsrc/u8g_font_timr12r.su ./Drivers/fntsrc/u8g_font_timr14.d ./Drivers/fntsrc/u8g_font_timr14.o ./Drivers/fntsrc/u8g_font_timr14.su ./Drivers/fntsrc/u8g_font_timr14r.d ./Drivers/fntsrc/u8g_font_timr14r.o ./Drivers/fntsrc/u8g_font_timr14r.su ./Drivers/fntsrc/u8g_font_timr18.d ./Drivers/fntsrc/u8g_font_timr18.o ./Drivers/fntsrc/u8g_font_timr18.su ./Drivers/fntsrc/u8g_font_timr18r.d ./Drivers/fntsrc/u8g_font_timr18r.o ./Drivers/fntsrc/u8g_font_timr18r.su ./Drivers/fntsrc/u8g_font_timr24.d ./Drivers/fntsrc/u8g_font_timr24.o ./Drivers/fntsrc/u8g_font_timr24.su ./Drivers/fntsrc/u8g_font_timr24n.d ./Drivers/fntsrc/u8g_font_timr24n.o ./Drivers/fntsrc/u8g_font_timr24n.su ./Drivers/fntsrc/u8g_font_timr24r.d ./Drivers/fntsrc/u8g_font_timr24r.o ./Drivers/fntsrc/u8g_font_timr24r.su ./Drivers/fntsrc/u8g_font_tpss.d ./Drivers/fntsrc/u8g_font_tpss.o ./Drivers/fntsrc/u8g_font_tpss.su ./Drivers/fntsrc/u8g_font_tpssb.d ./Drivers/fntsrc/u8g_font_tpssb.o ./Drivers/fntsrc/u8g_font_tpssb.su ./Drivers/fntsrc/u8g_font_tpssbn.d ./Drivers/fntsrc/u8g_font_tpssbn.o ./Drivers/fntsrc/u8g_font_tpssbn.su ./Drivers/fntsrc/u8g_font_tpssbr.d ./Drivers/fntsrc/u8g_font_tpssbr.o ./Drivers/fntsrc/u8g_font_tpssbr.su ./Drivers/fntsrc/u8g_font_tpssn.d ./Drivers/fntsrc/u8g_font_tpssn.o ./Drivers/fntsrc/u8g_font_tpssn.su ./Drivers/fntsrc/u8g_font_tpssr.d ./Drivers/fntsrc/u8g_font_tpssr.o ./Drivers/fntsrc/u8g_font_tpssr.su ./Drivers/fntsrc/u8g_font_trixel_square.d ./Drivers/fntsrc/u8g_font_trixel_square.o ./Drivers/fntsrc/u8g_font_trixel_square.su ./Drivers/fntsrc/u8g_font_trixel_squaren.d ./Drivers/fntsrc/u8g_font_trixel_squaren.o ./Drivers/fntsrc/u8g_font_trixel_squaren.su ./Drivers/fntsrc/u8g_font_trixel_squarer.d ./Drivers/fntsrc/u8g_font_trixel_squarer.o ./Drivers/fntsrc/u8g_font_trixel_squarer.su ./Drivers/fntsrc/u8g_font_u8glib_4.d ./Drivers/fntsrc/u8g_font_u8glib_4.o ./Drivers/fntsrc/u8g_font_u8glib_4.su ./Drivers/fntsrc/u8g_font_u8glib_4r.d ./Drivers/fntsrc/u8g_font_u8glib_4r.o ./Drivers/fntsrc/u8g_font_u8glib_4r.su ./Drivers/fntsrc/u8g_font_unifont.d ./Drivers/fntsrc/u8g_font_unifont.o ./Drivers/fntsrc/u8g_font_unifont.su ./Drivers/fntsrc/u8g_font_unifont_0_8.d ./Drivers/fntsrc/u8g_font_unifont_0_8.o ./Drivers/fntsrc/u8g_font_unifont_0_8.su ./Drivers/fntsrc/u8g_font_unifont_12_13.d ./Drivers/fntsrc/u8g_font_unifont_12_13.o ./Drivers/fntsrc/u8g_font_unifont_12_13.su ./Drivers/fntsrc/u8g_font_unifont_18_19.d ./Drivers/fntsrc/u8g_font_unifont_18_19.o ./Drivers/fntsrc/u8g_font_unifont_18_19.su ./Drivers/fntsrc/u8g_font_unifont_2_3.d ./Drivers/fntsrc/u8g_font_unifont_2_3.o ./Drivers/fntsrc/u8g_font_unifont_2_3.su ./Drivers/fntsrc/u8g_font_unifont_4_5.d ./Drivers/fntsrc/u8g_font_unifont_4_5.o ./Drivers/fntsrc/u8g_font_unifont_4_5.su ./Drivers/fntsrc/u8g_font_unifont_67_75.d ./Drivers/fntsrc/u8g_font_unifont_67_75.o ./Drivers/fntsrc/u8g_font_unifont_67_75.su ./Drivers/fntsrc/u8g_font_unifont_72_73.d ./Drivers/fntsrc/u8g_font_unifont_72_73.o ./Drivers/fntsrc/u8g_font_unifont_72_73.su ./Drivers/fntsrc/u8g_font_unifont_75r.d ./Drivers/fntsrc/u8g_font_unifont_75r.o ./Drivers/fntsrc/u8g_font_unifont_75r.su ./Drivers/fntsrc/u8g_font_unifont_76.d
	-$(RM) ./Drivers/fntsrc/u8g_font_unifont_76.o ./Drivers/fntsrc/u8g_font_unifont_76.su ./Drivers/fntsrc/u8g_font_unifont_77.d ./Drivers/fntsrc/u8g_font_unifont_77.o ./Drivers/fntsrc/u8g_font_unifont_77.su ./Drivers/fntsrc/u8g_font_unifont_78_79.d ./Drivers/fntsrc/u8g_font_unifont_78_79.o ./Drivers/fntsrc/u8g_font_unifont_78_79.su ./Drivers/fntsrc/u8g_font_unifont_86.d ./Drivers/fntsrc/u8g_font_unifont_86.o ./Drivers/fntsrc/u8g_font_unifont_86.su ./Drivers/fntsrc/u8g_font_unifont_8_9.d ./Drivers/fntsrc/u8g_font_unifont_8_9.o ./Drivers/fntsrc/u8g_font_unifont_8_9.su ./Drivers/fntsrc/u8g_font_unifontr.d ./Drivers/fntsrc/u8g_font_unifontr.o ./Drivers/fntsrc/u8g_font_unifontr.su

.PHONY: clean-Drivers-2f-fntsrc

