/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.12
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDial>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionConfiguration;
    QAction *actionDisconnected;
    QWidget *centralwidget;
    QLabel *label;
    QLabel *connectionStatus;
    QLabel *label_2;
    QGroupBox *analogInputBox;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QSlider *analogIn1_slider;
    QSlider *analogIn2_slider;
    QSlider *analogIn3_slider;
    QSlider *analogIn4_slider;
    QSlider *analogIn5_slider;
    QSlider *analogIn6_slider;
    QSlider *analogIn7_slider;
    QSlider *analogIn8_slider;
    QLabel *analogIn5_label;
    QLabel *analogIn6_label;
    QLabel *analogIn7_label;
    QLabel *analogIn8_label;
    QLabel *analogIn1_label;
    QLabel *analogIn2_label;
    QLabel *analogIn3_label;
    QLabel *analogIn4_label;
    QGroupBox *analogOutputBox;
    QLabel *label_20;
    QLabel *label_21;
    QDial *analogOutput1_dial;
    QDial *analogOutput2_dial;
    QLCDNumber *analogOutput1_lcd;
    QLCDNumber *analogOutput2_lcd;
    QGroupBox *digitalInputBox;
    QCheckBox *digitalInput2;
    QCheckBox *digitalInput6;
    QCheckBox *digitalInput7;
    QCheckBox *digitalInput5;
    QCheckBox *digitalInput4;
    QCheckBox *digitalInput3;
    QCheckBox *digitalInput1;
    QCheckBox *digitalInput8;
    QLabel *label_3;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QGroupBox *digitalOutputBox;
    QCheckBox *digitalOutput2;
    QCheckBox *digitalOutput6;
    QCheckBox *digitalOutput7;
    QCheckBox *digitalOutput5;
    QCheckBox *digitalOutput4;
    QCheckBox *digitalOutput3;
    QCheckBox *digitalOutput1;
    QCheckBox *digitalOutput8;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QPushButton *connectButton;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(755, 322);
        actionConfiguration = new QAction(MainWindow);
        actionConfiguration->setObjectName(QString::fromUtf8("actionConfiguration"));
        actionDisconnected = new QAction(MainWindow);
        actionDisconnected->setObjectName(QString::fromUtf8("actionDisconnected"));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(40, 30, 111, 21));
        QFont font;
        font.setBold(true);
        font.setItalic(true);
        font.setUnderline(true);
        font.setWeight(75);
        label->setFont(font);
        label->setAlignment(Qt::AlignCenter);
        connectionStatus = new QLabel(centralwidget);
        connectionStatus->setObjectName(QString::fromUtf8("connectionStatus"));
        connectionStatus->setGeometry(QRect(150, 30, 91, 21));
        QFont font1;
        font1.setBold(true);
        font1.setWeight(75);
        connectionStatus->setFont(font1);
        connectionStatus->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(300, 0, 201, 31));
        label_2->setFont(font);
        label_2->setAlignment(Qt::AlignCenter);
        analogInputBox = new QGroupBox(centralwidget);
        analogInputBox->setObjectName(QString::fromUtf8("analogInputBox"));
        analogInputBox->setGeometry(QRect(20, 70, 401, 181));
        QFont font2;
        font2.setPointSize(10);
        font2.setBold(true);
        font2.setWeight(75);
        analogInputBox->setFont(font2);
        label_4 = new QLabel(analogInputBox);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(20, 30, 61, 21));
        label_4->setFont(font2);
        label_4->setAlignment(Qt::AlignCenter);
        label_5 = new QLabel(analogInputBox);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(100, 30, 61, 21));
        label_5->setFont(font2);
        label_5->setAlignment(Qt::AlignCenter);
        label_6 = new QLabel(analogInputBox);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(180, 30, 61, 21));
        label_6->setFont(font2);
        label_6->setAlignment(Qt::AlignCenter);
        label_7 = new QLabel(analogInputBox);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(260, 30, 61, 21));
        label_7->setFont(font2);
        label_7->setAlignment(Qt::AlignCenter);
        label_8 = new QLabel(analogInputBox);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(260, 110, 61, 21));
        label_8->setFont(font2);
        label_8->setAlignment(Qt::AlignCenter);
        label_9 = new QLabel(analogInputBox);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(180, 110, 71, 21));
        label_9->setFont(font2);
        label_9->setAlignment(Qt::AlignCenter);
        label_10 = new QLabel(analogInputBox);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(20, 110, 61, 21));
        label_10->setFont(font2);
        label_10->setAlignment(Qt::AlignCenter);
        label_11 = new QLabel(analogInputBox);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(100, 110, 61, 21));
        label_11->setFont(font2);
        label_11->setAlignment(Qt::AlignCenter);
        analogIn1_slider = new QSlider(analogInputBox);
        analogIn1_slider->setObjectName(QString::fromUtf8("analogIn1_slider"));
        analogIn1_slider->setGeometry(QRect(20, 70, 61, 20));
        analogIn1_slider->setMaximum(100);
        analogIn1_slider->setOrientation(Qt::Horizontal);
        analogIn2_slider = new QSlider(analogInputBox);
        analogIn2_slider->setObjectName(QString::fromUtf8("analogIn2_slider"));
        analogIn2_slider->setGeometry(QRect(100, 70, 61, 20));
        analogIn2_slider->setMaximum(100);
        analogIn2_slider->setOrientation(Qt::Horizontal);
        analogIn3_slider = new QSlider(analogInputBox);
        analogIn3_slider->setObjectName(QString::fromUtf8("analogIn3_slider"));
        analogIn3_slider->setGeometry(QRect(180, 70, 61, 20));
        analogIn3_slider->setMaximum(100);
        analogIn3_slider->setOrientation(Qt::Horizontal);
        analogIn4_slider = new QSlider(analogInputBox);
        analogIn4_slider->setObjectName(QString::fromUtf8("analogIn4_slider"));
        analogIn4_slider->setGeometry(QRect(260, 70, 61, 20));
        analogIn4_slider->setMaximum(100);
        analogIn4_slider->setOrientation(Qt::Horizontal);
        analogIn5_slider = new QSlider(analogInputBox);
        analogIn5_slider->setObjectName(QString::fromUtf8("analogIn5_slider"));
        analogIn5_slider->setGeometry(QRect(20, 150, 61, 20));
        analogIn5_slider->setMaximum(100);
        analogIn5_slider->setOrientation(Qt::Horizontal);
        analogIn6_slider = new QSlider(analogInputBox);
        analogIn6_slider->setObjectName(QString::fromUtf8("analogIn6_slider"));
        analogIn6_slider->setGeometry(QRect(100, 150, 61, 20));
        analogIn6_slider->setMaximum(100);
        analogIn6_slider->setOrientation(Qt::Horizontal);
        analogIn7_slider = new QSlider(analogInputBox);
        analogIn7_slider->setObjectName(QString::fromUtf8("analogIn7_slider"));
        analogIn7_slider->setGeometry(QRect(180, 150, 61, 20));
        analogIn7_slider->setMaximum(100);
        analogIn7_slider->setOrientation(Qt::Horizontal);
        analogIn8_slider = new QSlider(analogInputBox);
        analogIn8_slider->setObjectName(QString::fromUtf8("analogIn8_slider"));
        analogIn8_slider->setGeometry(QRect(260, 150, 61, 20));
        analogIn8_slider->setMinimum(-50);
        analogIn8_slider->setMaximum(50);
        analogIn8_slider->setOrientation(Qt::Horizontal);
        analogIn5_label = new QLabel(analogInputBox);
        analogIn5_label->setObjectName(QString::fromUtf8("analogIn5_label"));
        analogIn5_label->setGeometry(QRect(30, 130, 41, 16));
        QFont font3;
        font3.setPointSize(8);
        font3.setBold(true);
        font3.setWeight(75);
        analogIn5_label->setFont(font3);
        analogIn5_label->setAlignment(Qt::AlignCenter);
        analogIn6_label = new QLabel(analogInputBox);
        analogIn6_label->setObjectName(QString::fromUtf8("analogIn6_label"));
        analogIn6_label->setGeometry(QRect(110, 130, 41, 16));
        analogIn6_label->setFont(font3);
        analogIn6_label->setAlignment(Qt::AlignCenter);
        analogIn7_label = new QLabel(analogInputBox);
        analogIn7_label->setObjectName(QString::fromUtf8("analogIn7_label"));
        analogIn7_label->setGeometry(QRect(190, 130, 41, 16));
        analogIn7_label->setFont(font3);
        analogIn7_label->setAlignment(Qt::AlignCenter);
        analogIn8_label = new QLabel(analogInputBox);
        analogIn8_label->setObjectName(QString::fromUtf8("analogIn8_label"));
        analogIn8_label->setGeometry(QRect(270, 130, 41, 16));
        analogIn8_label->setFont(font3);
        analogIn8_label->setAlignment(Qt::AlignCenter);
        analogIn1_label = new QLabel(analogInputBox);
        analogIn1_label->setObjectName(QString::fromUtf8("analogIn1_label"));
        analogIn1_label->setGeometry(QRect(30, 50, 41, 16));
        analogIn1_label->setFont(font3);
        analogIn1_label->setAlignment(Qt::AlignCenter);
        analogIn2_label = new QLabel(analogInputBox);
        analogIn2_label->setObjectName(QString::fromUtf8("analogIn2_label"));
        analogIn2_label->setGeometry(QRect(110, 50, 41, 16));
        analogIn2_label->setFont(font3);
        analogIn2_label->setAlignment(Qt::AlignCenter);
        analogIn3_label = new QLabel(analogInputBox);
        analogIn3_label->setObjectName(QString::fromUtf8("analogIn3_label"));
        analogIn3_label->setGeometry(QRect(190, 50, 41, 16));
        analogIn3_label->setFont(font3);
        analogIn3_label->setAlignment(Qt::AlignCenter);
        analogIn4_label = new QLabel(analogInputBox);
        analogIn4_label->setObjectName(QString::fromUtf8("analogIn4_label"));
        analogIn4_label->setGeometry(QRect(270, 50, 41, 16));
        analogIn4_label->setFont(font3);
        analogIn4_label->setAlignment(Qt::AlignCenter);
        analogOutputBox = new QGroupBox(centralwidget);
        analogOutputBox->setObjectName(QString::fromUtf8("analogOutputBox"));
        analogOutputBox->setGeometry(QRect(430, 90, 301, 151));
        analogOutputBox->setFont(font2);
        label_20 = new QLabel(analogOutputBox);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(70, 30, 61, 31));
        label_20->setFont(font3);
        label_20->setAlignment(Qt::AlignCenter);
        label_21 = new QLabel(analogOutputBox);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(190, 30, 61, 31));
        label_21->setFont(font3);
        label_21->setAlignment(Qt::AlignCenter);
        analogOutput1_dial = new QDial(analogOutputBox);
        analogOutput1_dial->setObjectName(QString::fromUtf8("analogOutput1_dial"));
        analogOutput1_dial->setGeometry(QRect(70, 50, 50, 64));
        analogOutput1_dial->setMaximum(50);
        analogOutput1_dial->setSingleStep(1);
        analogOutput2_dial = new QDial(analogOutputBox);
        analogOutput2_dial->setObjectName(QString::fromUtf8("analogOutput2_dial"));
        analogOutput2_dial->setGeometry(QRect(190, 50, 50, 64));
        analogOutput2_dial->setMaximum(50);
        analogOutput1_lcd = new QLCDNumber(analogOutputBox);
        analogOutput1_lcd->setObjectName(QString::fromUtf8("analogOutput1_lcd"));
        analogOutput1_lcd->setGeometry(QRect(73, 110, 51, 23));
        analogOutput1_lcd->setSmallDecimalPoint(true);
        analogOutput2_lcd = new QLCDNumber(analogOutputBox);
        analogOutput2_lcd->setObjectName(QString::fromUtf8("analogOutput2_lcd"));
        analogOutput2_lcd->setGeometry(QRect(190, 110, 51, 23));
        analogOutput2_lcd->setSmallDecimalPoint(true);
        analogOutput2_lcd->setSegmentStyle(QLCDNumber::Outline);
        digitalInputBox = new QGroupBox(centralwidget);
        digitalInputBox->setObjectName(QString::fromUtf8("digitalInputBox"));
        digitalInputBox->setGeometry(QRect(20, 250, 401, 61));
        digitalInputBox->setFont(font2);
        digitalInput2 = new QCheckBox(digitalInputBox);
        digitalInput2->setObjectName(QString::fromUtf8("digitalInput2"));
        digitalInput2->setGeometry(QRect(40, 20, 16, 17));
        digitalInput6 = new QCheckBox(digitalInputBox);
        digitalInput6->setObjectName(QString::fromUtf8("digitalInput6"));
        digitalInput6->setGeometry(QRect(120, 20, 16, 17));
        digitalInput7 = new QCheckBox(digitalInputBox);
        digitalInput7->setObjectName(QString::fromUtf8("digitalInput7"));
        digitalInput7->setGeometry(QRect(140, 20, 16, 17));
        digitalInput5 = new QCheckBox(digitalInputBox);
        digitalInput5->setObjectName(QString::fromUtf8("digitalInput5"));
        digitalInput5->setGeometry(QRect(100, 20, 16, 17));
        digitalInput4 = new QCheckBox(digitalInputBox);
        digitalInput4->setObjectName(QString::fromUtf8("digitalInput4"));
        digitalInput4->setGeometry(QRect(80, 20, 16, 17));
        digitalInput3 = new QCheckBox(digitalInputBox);
        digitalInput3->setObjectName(QString::fromUtf8("digitalInput3"));
        digitalInput3->setGeometry(QRect(60, 20, 16, 17));
        digitalInput1 = new QCheckBox(digitalInputBox);
        digitalInput1->setObjectName(QString::fromUtf8("digitalInput1"));
        digitalInput1->setGeometry(QRect(20, 20, 16, 17));
        digitalInput1->setChecked(false);
        digitalInput8 = new QCheckBox(digitalInputBox);
        digitalInput8->setObjectName(QString::fromUtf8("digitalInput8"));
        digitalInput8->setGeometry(QRect(160, 20, 16, 17));
        label_3 = new QLabel(digitalInputBox);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(20, 40, 16, 16));
        label_3->setAlignment(Qt::AlignCenter);
        label_22 = new QLabel(digitalInputBox);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(40, 40, 16, 16));
        label_22->setAlignment(Qt::AlignCenter);
        label_23 = new QLabel(digitalInputBox);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(60, 40, 16, 16));
        label_23->setAlignment(Qt::AlignCenter);
        label_24 = new QLabel(digitalInputBox);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(80, 40, 16, 16));
        label_24->setAlignment(Qt::AlignCenter);
        label_25 = new QLabel(digitalInputBox);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(100, 40, 16, 16));
        label_25->setAlignment(Qt::AlignCenter);
        label_26 = new QLabel(digitalInputBox);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(120, 40, 16, 16));
        label_26->setAlignment(Qt::AlignCenter);
        label_27 = new QLabel(digitalInputBox);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(140, 40, 16, 16));
        label_27->setAlignment(Qt::AlignCenter);
        label_28 = new QLabel(digitalInputBox);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(160, 40, 16, 16));
        label_28->setAlignment(Qt::AlignCenter);
        digitalOutputBox = new QGroupBox(centralwidget);
        digitalOutputBox->setObjectName(QString::fromUtf8("digitalOutputBox"));
        digitalOutputBox->setGeometry(QRect(430, 250, 301, 61));
        digitalOutputBox->setFont(font2);
        digitalOutput2 = new QCheckBox(digitalOutputBox);
        digitalOutput2->setObjectName(QString::fromUtf8("digitalOutput2"));
        digitalOutput2->setGeometry(QRect(40, 20, 16, 17));
        digitalOutput6 = new QCheckBox(digitalOutputBox);
        digitalOutput6->setObjectName(QString::fromUtf8("digitalOutput6"));
        digitalOutput6->setGeometry(QRect(120, 20, 16, 17));
        digitalOutput7 = new QCheckBox(digitalOutputBox);
        digitalOutput7->setObjectName(QString::fromUtf8("digitalOutput7"));
        digitalOutput7->setGeometry(QRect(140, 20, 16, 17));
        digitalOutput5 = new QCheckBox(digitalOutputBox);
        digitalOutput5->setObjectName(QString::fromUtf8("digitalOutput5"));
        digitalOutput5->setGeometry(QRect(100, 20, 16, 17));
        digitalOutput4 = new QCheckBox(digitalOutputBox);
        digitalOutput4->setObjectName(QString::fromUtf8("digitalOutput4"));
        digitalOutput4->setGeometry(QRect(80, 20, 16, 17));
        digitalOutput3 = new QCheckBox(digitalOutputBox);
        digitalOutput3->setObjectName(QString::fromUtf8("digitalOutput3"));
        digitalOutput3->setGeometry(QRect(60, 20, 16, 17));
        digitalOutput1 = new QCheckBox(digitalOutputBox);
        digitalOutput1->setObjectName(QString::fromUtf8("digitalOutput1"));
        digitalOutput1->setGeometry(QRect(20, 20, 16, 17));
        digitalOutput8 = new QCheckBox(digitalOutputBox);
        digitalOutput8->setObjectName(QString::fromUtf8("digitalOutput8"));
        digitalOutput8->setGeometry(QRect(160, 20, 16, 17));
        label_29 = new QLabel(digitalOutputBox);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(160, 40, 16, 16));
        label_29->setAlignment(Qt::AlignCenter);
        label_30 = new QLabel(digitalOutputBox);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(20, 40, 16, 16));
        label_30->setAlignment(Qt::AlignCenter);
        label_31 = new QLabel(digitalOutputBox);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(140, 40, 16, 16));
        label_31->setAlignment(Qt::AlignCenter);
        label_32 = new QLabel(digitalOutputBox);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(80, 40, 16, 16));
        label_32->setAlignment(Qt::AlignCenter);
        label_33 = new QLabel(digitalOutputBox);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(100, 40, 16, 16));
        label_33->setAlignment(Qt::AlignCenter);
        label_34 = new QLabel(digitalOutputBox);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(40, 40, 16, 16));
        label_34->setAlignment(Qt::AlignCenter);
        label_35 = new QLabel(digitalOutputBox);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(120, 40, 16, 16));
        label_35->setAlignment(Qt::AlignCenter);
        label_36 = new QLabel(digitalOutputBox);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(60, 40, 16, 16));
        label_36->setAlignment(Qt::AlignCenter);
        connectButton = new QPushButton(centralwidget);
        connectButton->setObjectName(QString::fromUtf8("connectButton"));
        connectButton->setGeometry(QRect(270, 30, 75, 23));
        MainWindow->setCentralWidget(centralwidget);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        actionConfiguration->setText(QApplication::translate("MainWindow", "Configuration", nullptr));
        actionDisconnected->setText(QApplication::translate("MainWindow", "Disconnected", nullptr));
        label->setText(QApplication::translate("MainWindow", "Serial Port status: ", nullptr));
        connectionStatus->setText(QApplication::translate("MainWindow", "DISCONNECTED", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Instrumento Virtual 2023", nullptr));
        analogInputBox->setTitle(QApplication::translate("MainWindow", "Entradas Analogicas", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Entrada 1", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "Entrada 2", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "Entrada 3", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "Entrada 4", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "Entrada 8", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "Entrada 7 ", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "Entrada 5", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "Entrada 6", nullptr));
        analogIn5_label->setText(QApplication::translate("MainWindow", "0 V", nullptr));
        analogIn6_label->setText(QApplication::translate("MainWindow", "0 V", nullptr));
        analogIn7_label->setText(QApplication::translate("MainWindow", "0 V", nullptr));
        analogIn8_label->setText(QApplication::translate("MainWindow", "0 V", nullptr));
        analogIn1_label->setText(QApplication::translate("MainWindow", "0 V", nullptr));
        analogIn2_label->setText(QApplication::translate("MainWindow", "0 V", nullptr));
        analogIn3_label->setText(QApplication::translate("MainWindow", "0 V", nullptr));
        analogIn4_label->setText(QApplication::translate("MainWindow", "0 V", nullptr));
        analogOutputBox->setTitle(QApplication::translate("MainWindow", "Salidas Analogicas", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "Salida 1", nullptr));
        label_21->setText(QApplication::translate("MainWindow", "Salida 2", nullptr));
        digitalInputBox->setTitle(QApplication::translate("MainWindow", "Entradas Digitales", nullptr));
        digitalInput2->setText(QString());
        digitalInput6->setText(QString());
        digitalInput7->setText(QString());
        digitalInput5->setText(QString());
        digitalInput4->setText(QString());
        digitalInput3->setText(QString());
        digitalInput1->setText(QString());
        digitalInput8->setText(QString());
        label_3->setText(QApplication::translate("MainWindow", "1", nullptr));
        label_22->setText(QApplication::translate("MainWindow", "2", nullptr));
        label_23->setText(QApplication::translate("MainWindow", "3", nullptr));
        label_24->setText(QApplication::translate("MainWindow", "4", nullptr));
        label_25->setText(QApplication::translate("MainWindow", "5", nullptr));
        label_26->setText(QApplication::translate("MainWindow", "6", nullptr));
        label_27->setText(QApplication::translate("MainWindow", "7", nullptr));
        label_28->setText(QApplication::translate("MainWindow", "8", nullptr));
        digitalOutputBox->setTitle(QApplication::translate("MainWindow", "Salidas Digitales", nullptr));
        digitalOutput2->setText(QString());
        digitalOutput6->setText(QString());
        digitalOutput7->setText(QString());
        digitalOutput5->setText(QString());
        digitalOutput4->setText(QString());
        digitalOutput3->setText(QString());
        digitalOutput1->setText(QString());
        digitalOutput8->setText(QString());
        label_29->setText(QApplication::translate("MainWindow", "8", nullptr));
        label_30->setText(QApplication::translate("MainWindow", "1", nullptr));
        label_31->setText(QApplication::translate("MainWindow", "7", nullptr));
        label_32->setText(QApplication::translate("MainWindow", "4", nullptr));
        label_33->setText(QApplication::translate("MainWindow", "5", nullptr));
        label_34->setText(QApplication::translate("MainWindow", "2", nullptr));
        label_35->setText(QApplication::translate("MainWindow", "6", nullptr));
        label_36->setText(QApplication::translate("MainWindow", "3", nullptr));
        connectButton->setText(QApplication::translate("MainWindow", "Connect", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
